"""
Interactive configuration editor.

Provides a guided interface for editing Django Matt configuration.
"""

from pathlib import Path
from typing import Any

from django_matt.cli.config.sections import (
    CacheSection,
    ConfigSection,
    DatabaseSection,
    GeneralSection,
    SecuritySection,
)
from django_matt.cli.console import console
from django_matt.cli.prompts import confirm, multiselect


class ConfigEditor:
    """
    Interactive configuration editor.

    Guides users through configuring their Django Matt project.
    """

    def __init__(self, output_path: str | Path = ".env"):
        self.output_path = Path(output_path)
        self.sections: list[ConfigSection] = [
            GeneralSection(),
            DatabaseSection(),
            CacheSection(),
            SecuritySection(),
        ]
        self.values: dict[str, dict[str, Any]] = {}

    def run(self, sections: list[str] | None = None) -> dict[str, str]:
        """
        Run the interactive configuration editor.

        Args:
            sections: List of section names to edit (None for all)

        Returns:
            Dictionary of environment variables
        """
        console.banner()
        console.header("Configuration Editor", "Configure your Django Matt project")

        # Filter sections if specified
        if sections:
            active_sections = [s for s in self.sections if s.name in sections]
        else:
            active_sections = self._select_sections()

        if not active_sections:
            console.warning("No sections selected. Exiting.")
            return {}

        # Collect values from each section
        all_env_vars: dict[str, str] = {}

        for section in active_sections:
            console.section(section.title)
            console.muted(section.description)
            console.newline()

            # Get values from prompts
            values = section.get_prompts()
            self.values[section.name] = values

            # Validate
            errors = section.validate(values)
            if errors:
                console.newline()
                for error in errors:
                    console.warning(error)

                if not confirm("Continue anyway?", default=False):
                    console.info(f"Skipping {section.title}")
                    continue

            # Convert to env vars
            env_vars = section.get_env_vars(values)
            all_env_vars.update(env_vars)

            console.success(f"{section.title} configured")
            console.newline()

        return all_env_vars

    def _select_sections(self) -> list[ConfigSection]:
        """Let user select which sections to configure."""
        choices = [{"name": f"{s.title} - {s.description}", "value": s.name} for s in self.sections]

        selected = multiselect(
            "Which sections would you like to configure?",
            choices=choices,
            default=[s.name for s in self.sections],
        )

        return [s for s in self.sections if s.name in selected]

    def preview_env_file(self, env_vars: dict[str, str]) -> str:
        """
        Generate preview of the .env file.

        Args:
            env_vars: Environment variables to include

        Returns:
            Content of the .env file
        """
        lines = ["# Django Matt Configuration", "# Generated by config editor", ""]

        # Group by prefix
        groups: dict[str, list[tuple[str, str]]] = {}

        for key, value in env_vars.items():
            prefix = key.split("_")[0] if "_" in key else "GENERAL"
            if prefix not in groups:
                groups[prefix] = []
            groups[prefix].append((key, value))

        for group_name, items in groups.items():
            lines.append(f"# {group_name.title()} Settings")
            for key, value in sorted(items):
                lines.append(f"{key}={value}")
            lines.append("")

        return "\n".join(lines)

    def write_env_file(self, env_vars: dict[str, str], force: bool = False) -> bool:
        """
        Write the .env file.

        Args:
            env_vars: Environment variables to write
            force: Overwrite existing file

        Returns:
            True if file was written
        """
        if self.output_path.exists() and not force:
            console.warning(f"File {self.output_path} already exists")
            if not confirm("Overwrite?", default=False):
                console.info("File not written")
                return False

        content = self.preview_env_file(env_vars)
        self.output_path.write_text(content)
        console.file_created(self.output_path)
        return True

    def show_summary(self, env_vars: dict[str, str]) -> None:
        """
        Show a summary of the configuration.

        Args:
            env_vars: Environment variables to summarize
        """
        console.section("Configuration Summary")

        # Group by section
        data = []
        for key, value in sorted(env_vars.items()):
            # Mask sensitive values
            display_value = value
            if any(s in key.lower() for s in ["password", "secret", "key", "token"]):
                display_value = "*" * 8 if value else "(empty)"

            data.append({"Setting": key, "Value": display_value})

        console.table(data)

    def run_full_wizard(self, force: bool = False) -> bool:
        """
        Run the full configuration wizard.

        Args:
            force: Overwrite existing files

        Returns:
            True if configuration was written
        """
        env_vars = self.run()

        if not env_vars:
            return False

        # Show summary
        self.show_summary(env_vars)
        console.newline()

        # Preview
        content = self.preview_env_file(env_vars)
        console.code(content, language="bash", title=f"Preview: {self.output_path}")
        console.newline()

        # Confirm and write
        if confirm("Write this configuration?", default=True):
            return self.write_env_file(env_vars, force=force)

        console.info("Configuration not written")
        return False
