# Generated by Django 6.0.5 on 2026-05-19 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("devops", "DevOps"),
                            ("database", "Database"),
                            ("mobile", "Mobile"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("level", models.IntegerField(default=3)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "skills",
                "ordering": ["category", "order", "name"],
            },
        ),
    ]
