"""
Django settings for {{ project_name }}.

Generated by django-matt startapi (internal-tools template).
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "change-me-in-production")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS: list[str] = os.environ.get("ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_matt",
    "{{ project_name }}_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_matt.core.errors.ErrorMiddleware",
    "django_matt.multitenancy.TenantMiddlewareAsync",
    "django_matt.observability.ObservabilityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{ project_name }}"),
        "USER": os.environ.get("POSTGRES_USER", "{{ project_name }}"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "{{ project_name }}"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = False
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Django Matt — JWT
DJANGO_MATT_JWT = {
    "SECRET_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": 60 * 15,
    "REFRESH_TOKEN_LIFETIME": 60 * 60 * 24 * 7,
    "ALGORITHM": "HS256",
}

# Redis cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://localhost:6379/0"),
    }
}

# SSO / SAML (configure with your IdP)
DJANGO_MATT_SSO = {
    "ENABLED": False,  # set True once IdP is configured
    "PROVIDER": "saml",
    "METADATA_URL": "",
    "ENTITY_ID": "",
    "ACS_URL": "",
}

# Audit logging
DJANGO_MATT_AUDIT = {
    "ENABLED": True,
    "LOG_READS": False,
    "LOG_WRITES": True,
    "EXCLUDE_PATHS": ["/health/", "/static/"],
}

# Feature flags
DJANGO_MATT_FLAGS = {
    "BACKEND": "db",  # "db", "redis", or "launchdarkly"
    "CACHE_TTL": 60,
}

# Analytics
DJANGO_MATT_ANALYTICS = {
    "ENABLED": True,
    "BACKEND": "db",
    "SESSION_TTL": 1800,
}

# Django Unfold admin theme
UNFOLD = {
    "SITE_TITLE": "{{ project_name }}",
    "SITE_HEADER": "{{ project_name }} Admin",
}
