"""
Django Matt CRUD generator command.

This command generates CRUD controllers, schemas, services, admin, and tests for Django models.
By default, it generates a service layer for business logic (use --no-service to skip).

Usage:
    python manage.py generate_crud myapp.MyModel              # Includes service layer by default
    python manage.py generate_crud myapp.MyModel --no-service # Skip service layer
    python manage.py generate_crud myapp.MyModel --with-admin # Add Django Unfold admin
    python manage.py generate_crud myapp.MyModel --full       # All: controller, schema, service, admin, tests
    python manage.py generate_crud myapp.MyModel --with-tests
    python manage.py generate_crud myapp.MyModel --permissions IsAuthenticated
    python manage.py generate_crud myapp.MyModel --dry-run    # Preview without writing
"""

from pathlib import Path
from typing import Any

from django.apps import apps
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField, OneToOneField

from django_matt.cli import GeneratorCommand


class Command(GeneratorCommand):
    help = "Generate CRUD controllers, schemas, and tests for Django models"

    def add_arguments(self, parser):
        super().add_arguments(parser)
        parser.add_argument(
            "model",
            nargs="?",  # Optional when using wizard mode
            help="The model to generate CRUD for (format: app_name.ModelName)",
        )
        parser.add_argument(
            "--output-dir",
            default=None,
            help="Directory to output the generated files (default: app directory)",
        )
        parser.add_argument(
            "--prefix",
            default=None,
            help="URL prefix for the controller (default: model name in lowercase plural)",
        )
        # Note: --force and --dry-run are provided by GeneratorCommand
        parser.add_argument(
            "--components",
            nargs="+",
            default=["controller", "schema"],
            choices=["controller", "schema", "test", "all"],
            help="Components to generate (default: controller schema)",
        )
        parser.add_argument(
            "--permissions",
            nargs="+",
            default=[],
            help="Permission classes to use (e.g., IsAuthenticated IsAdmin)",
        )
        parser.add_argument(
            "--with-tests",
            action="store_true",
            help="Also generate test file",
        )
        parser.add_argument(
            "--pagination",
            action="store_true",
            default=True,
            help="Include pagination in list endpoint (default: True)",
        )
        parser.add_argument(
            "--filtering",
            action="store_true",
            default=False,
            help="Include filtering support",
        )
        parser.add_argument(
            "--soft-delete",
            action="store_true",
            default=False,
            help="Use soft delete instead of hard delete",
        )
        parser.add_argument(
            "--no-service",
            action="store_true",
            help="Skip generating the service layer (service is included by default)",
        )
        parser.add_argument(
            "--with-admin",
            action="store_true",
            help="Generate Django Unfold admin configuration",
        )
        parser.add_argument(
            "--full",
            action="store_true",
            help="Generate all components: controller, schema, service, admin, tests",
        )

    def handle(self, *args, **options):
        model_path = options.get("model")
        wizard_mode = options.get("wizard", False)

        # Run wizard if requested or if model not provided
        if wizard_mode or not model_path:
            model_path, options = self._run_wizard(options)
            if not model_path:
                return

        output_dir = options["output_dir"]
        prefix = options["prefix"]
        components = options["components"]
        permissions = options["permissions"]
        with_tests = options["with_tests"]
        pagination = options["pagination"]
        filtering = options["filtering"]
        soft_delete = options["soft_delete"]
        no_service = options["no_service"]
        with_admin = options["with_admin"]
        full = options["full"]

        # Service layer is generated by default unless --no-service is passed
        with_service = not no_service

        # Handle --full flag
        if full:
            components = ["controller", "schema", "test"]
            with_service = True  # Override --no-service if --full is used
            with_admin = True

        if "all" in components:
            components = ["controller", "schema", "test"]

        if with_tests and "test" not in components:
            components.append("test")

        # Parse model path
        try:
            app_label, model_name = model_path.split(".")
        except ValueError:
            self.error("Model must be specified in the format app_name.ModelName", raise_error=True)
            return

        # Get the model
        try:
            model = apps.get_model(app_label, model_name)
        except LookupError:
            self.error(f"Model {model_path} not found", raise_error=True)
            return

        # Show header
        self.header(f"Generate CRUD for {model_name}", f"App: {app_label}")

        # Determine output directory
        if output_dir is None:
            app_config = apps.get_app_config(app_label)
            output_dir = Path(app_config.path)
        else:
            output_dir = Path(output_dir)

        # Determine prefix (pluralize model name)
        if prefix is None:
            prefix = self._pluralize(model_name.lower())

        # Get model fields
        fields = self._get_model_fields(model)

        # Show what will be generated
        self.section("Components")
        gen_items = []
        if "schema" in components:
            gen_items.append("schemas.py")
        if "controller" in components:
            gen_items.append("controllers.py")
        if "test" in components:
            gen_items.append("tests.py")
        if with_service:
            gen_items.append("services.py")
        if with_admin:
            gen_items.append("admin.py")

        for item in gen_items:
            self.console.list_item(item, bullet="•", style="cyan")

        self.console.newline()

        # Store generation context
        context = {
            "model": model,
            "model_name": model_name,
            "app_label": app_label,
            "prefix": prefix,
            "fields": fields,
            "permissions": permissions,
            "pagination": pagination,
            "filtering": filtering,
            "soft_delete": soft_delete,
            "with_service": with_service,
        }

        # Generate components
        if "schema" in components:
            content = self._generate_schema_content(context)
            self.write_file(output_dir / "schemas.py", content, preview=not self._dry_run)

        if "controller" in components:
            content = self._generate_controller_content(context)
            self.write_file(output_dir / "controllers.py", content, preview=not self._dry_run)

        if "test" in components:
            content = self._generate_test_content(context)
            self.write_file(output_dir / "tests.py", content, preview=not self._dry_run)

        # Generate service layer
        if with_service:
            content = self._generate_service_content(context)
            self.write_file(output_dir / "services.py", content, preview=not self._dry_run)

        # Generate admin
        if with_admin:
            content = self._generate_admin_content(context)
            self.write_file(output_dir / "admin.py", content, preview=not self._dry_run)

        # Show summary
        self.show_summary()

        # Show next steps
        if not self._dry_run and self.total_changes > 0:
            next_steps = [
                f"Review generated files in {output_dir}",
                "Register controller in your API:",
            ]
            next_steps.append(f"  from {app_label}.controllers import {model_name}Controller")
            next_steps.append(f"  api.register_controller({model_name}Controller)")

            if with_service:
                next_steps.append(f"Add your business logic in {output_dir}/services.py")

            if with_admin:
                next_steps.append("Admin is auto-registered via @register_admin decorator")

            self.next_steps(next_steps)

    def _pluralize(self, word: str) -> str:
        """Simple pluralization."""
        if word.endswith("y"):
            return word[:-1] + "ies"
        if word.endswith(("s", "x", "z", "ch", "sh")):
            return word + "es"
        return word + "s"

    def _run_wizard(self, options: dict) -> tuple[str | None, dict]:
        """Run interactive wizard for CRUD generation."""
        self.console.banner()
        self.header("CRUD Generator Wizard", "Interactive setup for generating CRUD components")

        # Get all available models
        all_models = []
        for app_config in apps.get_app_configs():
            # Skip Django internal apps
            if app_config.name.startswith("django."):
                continue

            for model in app_config.get_models():
                model_path = f"{app_config.label}.{model.__name__}"
                all_models.append(model_path)

        if not all_models:
            self.warning("No models found in your apps")
            return None, options

        # Step 1: Select model
        self.console.step(1, "Select a model", total=4)
        model_path = self.prompt_select(
            "Which model do you want to generate CRUD for?",
            choices=sorted(all_models),
        )

        if not model_path:
            self.warning("No model selected")
            return None, options

        # Step 2: Select components
        self.console.newline()
        self.console.step(2, "Select components", total=4)
        component_choices = [
            {"name": "Controller (API endpoints)", "value": "controller", "checked": True},
            {"name": "Schema (Pydantic models)", "value": "schema", "checked": True},
            {"name": "Service layer (business logic)", "value": "service", "checked": True},
            {"name": "Admin (Django Unfold)", "value": "admin", "checked": False},
            {"name": "Tests", "value": "test", "checked": False},
        ]

        selected = self.prompt_multiselect(
            "Which components do you want to generate?",
            choices=[c["name"] for c in component_choices],
            default=[c["name"] for c in component_choices if c.get("checked")],
        )

        if not selected:
            self.warning("No components selected")
            return None, options

        # Map selections back to values
        selected_values = []
        for choice in component_choices:
            if choice["name"] in selected:
                selected_values.append(choice["value"])

        # Update options based on selections
        options["components"] = [
            v for v in selected_values if v in ("controller", "schema", "test")
        ]
        options["no_service"] = "service" not in selected_values
        options["with_admin"] = "admin" in selected_values
        options["with_tests"] = "test" in selected_values

        # Step 3: Configuration options
        self.console.newline()
        self.console.step(3, "Configure options", total=4)

        # Permissions
        perm_choice = self.prompt_select(
            "What authentication should be required?",
            choices=[
                "None (public endpoints)",
                "IsAuthenticated (any logged-in user)",
                "IsAdmin (admin users only)",
                "Custom (specify later)",
            ],
            default="IsAuthenticated (any logged-in user)",
        )

        if "IsAuthenticated" in perm_choice:
            options["permissions"] = ["IsAuthenticated"]
        elif "IsAdmin" in perm_choice:
            options["permissions"] = ["IsAuthenticated", "IsAdmin"]
        else:
            options["permissions"] = []

        # Soft delete
        soft_delete = self.prompt_confirm(
            "Use soft delete (mark as deleted instead of removing)?",
            default=False,
        )
        options["soft_delete"] = soft_delete

        # Step 4: Confirm
        self.console.newline()
        self.console.step(4, "Review and confirm", total=4)

        self.section("Summary")
        summary_data = [
            {"Setting": "Model", "Value": model_path},
            {"Setting": "Components", "Value": ", ".join(selected_values)},
            {"Setting": "Permissions", "Value": ", ".join(options["permissions"]) or "None"},
            {"Setting": "Soft Delete", "Value": "Yes" if soft_delete else "No"},
        ]
        self.table(summary_data)

        self.console.newline()
        if not self.prompt_confirm("Generate CRUD with these settings?", default=True):
            self.info("Cancelled")
            return None, options

        self.console.newline()
        return model_path, options

    def _get_model_fields(self, model: models.Model) -> list[dict[str, Any]]:
        """Get field information from a Django model."""
        fields = []

        for field in model._meta.fields:
            field_info = {
                "name": field.name,
                "type": self._get_python_type(field),
                "pydantic_type": self._get_pydantic_type(field),
                "required": not field.null and not field.blank and not field.has_default(),
                "has_default": field.has_default(),
                "default": field.default if field.has_default() else None,
                "is_pk": field.primary_key,
                "is_auto": field.primary_key
                and hasattr(field, "auto_created")
                and field.auto_created,
                "is_relation": isinstance(field, (ForeignKey, OneToOneField)),
                "is_m2m": False,
                "relation_type": self._get_relation_type(field),
                "related_model": self._get_related_model(field),
                "max_length": getattr(field, "max_length", None),
                "help_text": field.help_text or "",
                "verbose_name": str(field.verbose_name),
            }
            fields.append(field_info)

        # Add many-to-many fields
        for field in model._meta.many_to_many:
            field_info = {
                "name": field.name,
                "type": "list[int]",
                "pydantic_type": "list[int]",
                "required": False,
                "has_default": True,
                "default": [],
                "is_pk": False,
                "is_auto": False,
                "is_relation": True,
                "is_m2m": True,
                "relation_type": "many_to_many",
                "related_model": field.related_model.__name__,
                "max_length": None,
                "help_text": field.help_text or "",
                "verbose_name": str(field.verbose_name),
            }
            fields.append(field_info)

        return fields

    def _get_python_type(self, field: models.Field) -> str:
        """Convert Django field type to Python type."""
        type_map = {
            models.CharField: "str",
            models.TextField: "str",
            models.EmailField: "str",
            models.URLField: "str",
            models.SlugField: "str",
            models.IntegerField: "int",
            models.BigIntegerField: "int",
            models.SmallIntegerField: "int",
            models.PositiveIntegerField: "int",
            models.PositiveSmallIntegerField: "int",
            models.PositiveBigIntegerField: "int",
            models.AutoField: "int",
            models.BigAutoField: "int",
            models.BooleanField: "bool",
            models.NullBooleanField: "bool | None",
            models.FloatField: "float",
            models.DecimalField: "float",
            models.DateField: "date",
            models.DateTimeField: "datetime",
            models.TimeField: "time",
            models.DurationField: "timedelta",
            models.JSONField: "dict",
            models.UUIDField: "UUID",
            models.BinaryField: "bytes",
            models.FileField: "str",
            models.ImageField: "str",
            ForeignKey: "int",
            OneToOneField: "int",
        }

        for field_class, python_type in type_map.items():
            if isinstance(field, field_class):
                return python_type

        return "Any"

    def _get_pydantic_type(self, field: models.Field) -> str:
        """Get Pydantic-compatible type annotation."""
        base_type = self._get_python_type(field)

        # Add Field constraints for certain types
        if isinstance(field, models.CharField) and field.max_length:
            return "str"  # Will add Field(max_length=...) separately
        if isinstance(field, models.EmailField):
            return "EmailStr"
        if isinstance(field, models.URLField):
            return "HttpUrl"

        return base_type

    def _get_relation_type(self, field: models.Field) -> str | None:
        """Get the type of relation for a field."""
        if isinstance(field, ForeignKey):
            return "foreign_key"
        if isinstance(field, OneToOneField):
            return "one_to_one"
        if isinstance(field, ManyToManyField):
            return "many_to_many"
        return None

    def _get_related_model(self, field: models.Field) -> str | None:
        """Get the related model name for a relation field."""
        if hasattr(field, "related_model") and field.related_model:
            return field.related_model.__name__
        return None

    def _generate_schema_content(self, context: dict) -> str:
        """Generate Pydantic schema classes for a model."""
        model_name = context["model_name"]
        fields = context["fields"]

        # Determine imports needed
        imports = self._get_schema_imports(fields)

        # Build schema content
        lines = [imports, ""]

        # Base response schema
        lines.append(f"class {model_name}Schema(BaseModel):")
        lines.append(f'    """Response schema for {model_name}."""')
        lines.append("")

        for field in fields:
            if field["is_auto"]:
                lines.append(f"    {field['name']}: int")
            elif field["required"]:
                lines.append(f"    {field['name']}: {field['pydantic_type']}")
            else:
                lines.append(f"    {field['name']}: {field['pydantic_type']} | None = None")

        lines.append("")
        lines.append("    class Config:")
        lines.append("        from_attributes = True")
        lines.append("")

        # Create schema (for POST)
        lines.append("")
        lines.append(f"class {model_name}CreateSchema(BaseModel):")
        lines.append(f'    """Schema for creating a {model_name}."""')
        lines.append("")

        for field in fields:
            if field["is_auto"] or field["is_pk"]:
                continue  # Skip auto fields in create

            if field["required"]:
                if field["max_length"]:
                    lines.append(
                        f"    {field['name']}: str = Field(max_length={field['max_length']})"
                    )
                else:
                    lines.append(f"    {field['name']}: {field['pydantic_type']}")
            else:
                default = "None"
                if field["is_m2m"]:
                    default = "Field(default_factory=list)"
                lines.append(f"    {field['name']}: {field['pydantic_type']} | None = {default}")

        lines.append("")

        # Update schema (for PUT/PATCH)
        lines.append("")
        lines.append(f"class {model_name}UpdateSchema(BaseModel):")
        lines.append(f'    """Schema for updating a {model_name}."""')
        lines.append("")

        for field in fields:
            if field["is_auto"] or field["is_pk"]:
                continue

            lines.append(f"    {field['name']}: {field['pydantic_type']} | None = None")

        lines.append("")

        # List schema
        lines.append("")
        lines.append(f"class {model_name}ListSchema(BaseModel):")
        lines.append(f'    """Schema for list of {model_name} objects."""')
        lines.append("")
        lines.append(f"    items: list[{model_name}Schema]")
        lines.append("    total: int")
        lines.append("    page: int = 1")
        lines.append("    page_size: int = 20")

        return "\n".join(lines)

    def _get_schema_imports(self, fields: list[dict]) -> str:
        """Generate import statements for schemas."""
        imports = ["from pydantic import BaseModel, Field"]

        # Check if we need special types
        needs_datetime = any(f["type"] == "datetime" for f in fields)
        needs_date = any(f["type"] == "date" for f in fields)
        needs_time = any(f["type"] == "time" for f in fields)
        needs_uuid = any(f["type"] == "UUID" for f in fields)
        needs_email = any(f["pydantic_type"] == "EmailStr" for f in fields)
        needs_url = any(f["pydantic_type"] == "HttpUrl" for f in fields)
        needs_any = any(f["type"] == "Any" for f in fields)

        typing_imports = []
        if needs_any:
            typing_imports.append("Any")

        if typing_imports:
            imports.insert(0, f"from typing import {', '.join(typing_imports)}")

        datetime_imports = []
        if needs_datetime:
            datetime_imports.append("datetime")
        if needs_date:
            datetime_imports.append("date")
        if needs_time:
            datetime_imports.append("time")

        if datetime_imports:
            imports.insert(0, f"from datetime import {', '.join(datetime_imports)}")

        if needs_uuid:
            imports.insert(0, "from uuid import UUID")

        pydantic_extras = []
        if needs_email:
            pydantic_extras.append("EmailStr")
        if needs_url:
            pydantic_extras.append("HttpUrl")

        if pydantic_extras:
            imports[imports.index("from pydantic import BaseModel, Field")] = (
                f"from pydantic import BaseModel, Field, {', '.join(pydantic_extras)}"
            )

        return "\n".join(imports)

    def _generate_controller_content(self, context: dict) -> str:
        """Generate a CRUD controller for a model."""
        model_name = context["model_name"]
        app_label = context["app_label"]
        prefix = context["prefix"]
        permissions = context["permissions"]
        pagination = context["pagination"]
        soft_delete = context["soft_delete"]
        with_service = context.get("with_service", False)

        lines = []

        # Imports
        if not with_service:
            lines.append("from django.http import Http404")
            lines.append("from django.db.models import Q")
            lines.append("")
        lines.append("from django_matt.core.controller import APIController")
        lines.append("from django_matt.core.router import get, post, put, patch, delete")

        if permissions:
            perm_imports = ", ".join(permissions)
            lines.append(f"from django_matt.permissions import {perm_imports}")

        lines.append("")
        if not with_service:
            lines.append(f"from .models import {model_name}")
        lines.append("from .schemas import (")
        lines.append(f"    {model_name}Schema,")
        lines.append(f"    {model_name}CreateSchema,")
        lines.append(f"    {model_name}UpdateSchema,")
        lines.append(f"    {model_name}ListSchema,")
        lines.append(")")

        if with_service:
            lines.append(f"from .services import {model_name}Service")

        lines.append("")
        lines.append("")

        # Controller class
        lines.append(f"class {model_name}Controller(APIController):")
        lines.append(f'    """CRUD controller for {model_name}."""')
        lines.append("")
        lines.append(f'    prefix = "/{prefix}"')
        lines.append(f'    tags = ["{model_name}"]')

        if permissions:
            lines.append(f"    permission_classes = [{', '.join(permissions)}]")

        lines.append("")

        # Add service initialization if using service layer
        if with_service:
            lines.append("    def __init__(self):")
            lines.append(f"        self.service = {model_name}Service()")
            lines.append("")

        # List endpoint
        lines.append('    @get("/")')
        lines.append(f"    async def list_{prefix}(")
        lines.append("        self,")
        lines.append("        request,")
        if pagination:
            lines.append("        page: int = 1,")
            lines.append("        page_size: int = 20,")
        lines.append("        search: str | None = None,")
        lines.append(f"    ) -> {model_name}ListSchema:")
        lines.append(f'        """List all {model_name} objects."""')

        if with_service:
            # Service-based implementation
            lines.append("        items, total = await self.service.list(")
            if pagination:
                lines.append("            page=page,")
                lines.append("            page_size=page_size,")
            lines.append("            search=search,")
            lines.append("        )")
            lines.append("")
            lines.append(f"        return {model_name}ListSchema(")
            lines.append(
                f"            items=[{model_name}Schema.model_validate(item) for item in items],"
            )
            lines.append("            total=total,")
            if pagination:
                lines.append("            page=page,")
                lines.append("            page_size=page_size,")
            lines.append("        )")
        else:
            # Direct implementation
            lines.append(f"        queryset = {model_name}.objects.all()")
            lines.append("")
            lines.append("        # Apply search filter")
            lines.append("        if search:")
            lines.append("            queryset = queryset.filter(")
            lines.append("                Q(id__icontains=search)  # Add more searchable fields")
            lines.append("            )")
            lines.append("")

            if pagination:
                lines.append("        # Get total count")
                lines.append("        total = await queryset.acount()")
                lines.append("")
                lines.append("        # Apply pagination")
                lines.append("        offset = (page - 1) * page_size")
                lines.append(
                    "        items = [item async for item in queryset[offset:offset + page_size]]"
                )
                lines.append("")
                lines.append(f"        return {model_name}ListSchema(")
                lines.append(
                    f"            items=[{model_name}Schema.model_validate(item) for item in items],"
                )
                lines.append("            total=total,")
                lines.append("            page=page,")
                lines.append("            page_size=page_size,")
                lines.append("        )")
            else:
                lines.append("        items = [item async for item in queryset]")
                lines.append(f"        return {model_name}ListSchema(")
                lines.append(
                    f"            items=[{model_name}Schema.model_validate(item) for item in items],"
                )
                lines.append("            total=len(items),")
                lines.append("        )")

        lines.append("")

        # Get single endpoint
        lines.append('    @get("/{id}")')
        lines.append(
            f"    async def get_{model_name.lower()}(self, request, id: int) -> {model_name}Schema:"
        )
        lines.append(f'        """Get a single {model_name} by ID."""')

        if with_service:
            lines.append("        item = await self.service.get(id)")
            lines.append(f"        return {model_name}Schema.model_validate(item)")
        else:
            lines.append("        try:")
            lines.append(f"            item = await {model_name}.objects.aget(pk=id)")
            lines.append(f"        except {model_name}.DoesNotExist:")
            lines.append(f'            raise Http404("{model_name} not found")')
            lines.append(f"        return {model_name}Schema.model_validate(item)")

        lines.append("")

        # Create endpoint
        lines.append('    @post("/")')
        lines.append(f"    async def create_{model_name.lower()}(")
        lines.append("        self,")
        lines.append("        request,")
        lines.append(f"        data: {model_name}CreateSchema,")
        lines.append(f"    ) -> {model_name}Schema:")
        lines.append(f'        """Create a new {model_name}."""')

        if with_service:
            lines.append("        item = await self.service.create(data, user=request.user)")
            lines.append(f"        return {model_name}Schema.model_validate(item)")
        else:
            lines.append(f"        item = await {model_name}.objects.acreate(**data.model_dump())")
            lines.append(f"        return {model_name}Schema.model_validate(item)")

        lines.append("")

        # Update endpoint (PUT - full update)
        lines.append('    @put("/{id}")')
        lines.append(f"    async def update_{model_name.lower()}(")
        lines.append("        self,")
        lines.append("        request,")
        lines.append("        id: int,")
        lines.append(f"        data: {model_name}UpdateSchema,")
        lines.append(f"    ) -> {model_name}Schema:")
        lines.append(f'        """Update a {model_name} (full update)."""')

        if with_service:
            lines.append("        item = await self.service.update(id, data, partial=False)")
            lines.append(f"        return {model_name}Schema.model_validate(item)")
        else:
            lines.append("        try:")
            lines.append(f"            item = await {model_name}.objects.aget(pk=id)")
            lines.append(f"        except {model_name}.DoesNotExist:")
            lines.append(f'            raise Http404("{model_name} not found")')
            lines.append("")
            lines.append("        for key, value in data.model_dump(exclude_unset=True).items():")
            lines.append("            setattr(item, key, value)")
            lines.append("        await item.asave()")
            lines.append(f"        return {model_name}Schema.model_validate(item)")

        lines.append("")

        # Patch endpoint (partial update)
        lines.append('    @patch("/{id}")')
        lines.append(f"    async def patch_{model_name.lower()}(")
        lines.append("        self,")
        lines.append("        request,")
        lines.append("        id: int,")
        lines.append(f"        data: {model_name}UpdateSchema,")
        lines.append(f"    ) -> {model_name}Schema:")
        lines.append(f'        """Partially update a {model_name}."""')

        if with_service:
            lines.append("        item = await self.service.update(id, data, partial=True)")
            lines.append(f"        return {model_name}Schema.model_validate(item)")
        else:
            lines.append("        try:")
            lines.append(f"            item = await {model_name}.objects.aget(pk=id)")
            lines.append(f"        except {model_name}.DoesNotExist:")
            lines.append(f'            raise Http404("{model_name} not found")')
            lines.append("")
            lines.append("        for key, value in data.model_dump(exclude_unset=True).items():")
            lines.append("            if value is not None:")
            lines.append("                setattr(item, key, value)")
            lines.append("        await item.asave()")
            lines.append(f"        return {model_name}Schema.model_validate(item)")

        lines.append("")

        # Delete endpoint
        lines.append('    @delete("/{id}")')
        lines.append(f"    async def delete_{model_name.lower()}(self, request, id: int) -> dict:")
        lines.append(f'        """Delete a {model_name}."""')

        if with_service:
            lines.append("        await self.service.delete(id)")
            lines.append(
                f'        return {{"success": True, "message": f"{model_name} {{id}} deleted"}}'
            )
        else:
            lines.append("        try:")
            lines.append(f"            item = await {model_name}.objects.aget(pk=id)")
            lines.append(f"        except {model_name}.DoesNotExist:")
            lines.append(f'            raise Http404("{model_name} not found")')
            lines.append("")

            if soft_delete:
                lines.append("        # Soft delete")
                lines.append("        item.is_deleted = True")
                lines.append("        await item.asave()")
            else:
                lines.append("        await item.adelete()")

            lines.append(
                f'        return {{"success": True, "message": f"{model_name} {{id}} deleted"}}'
            )

        return "\n".join(lines)

    def _generate_test_content(self, context: dict) -> str:
        """Generate test file for the CRUD controller."""
        model_name = context["model_name"]
        app_label = context["app_label"]
        prefix = context["prefix"]

        lines = []

        # Imports
        lines.append("import pytest")
        lines.append("from django.test import AsyncClient")
        lines.append("")
        lines.append(f"from .models import {model_name}")
        lines.append(f"from .schemas import {model_name}CreateSchema")
        lines.append("")
        lines.append("")

        # Test class
        lines.append("@pytest.mark.django_db")
        lines.append(f"class Test{model_name}Controller:")
        lines.append(f'    """Tests for {model_name} CRUD endpoints."""')
        lines.append("")
        lines.append(f'    base_url = "/api/{prefix}"')
        lines.append("")

        # Test list
        lines.append("    @pytest.mark.asyncio")
        lines.append(f"    async def test_list_{prefix}(self, async_client: AsyncClient):")
        lines.append(f'        """Test listing {model_name} objects."""')
        lines.append("        response = await async_client.get(self.base_url)")
        lines.append("        assert response.status_code == 200")
        lines.append("        data = response.json()")
        lines.append('        assert "items" in data')
        lines.append('        assert "total" in data')
        lines.append("")

        # Test create
        lines.append("    @pytest.mark.asyncio")
        lines.append(
            f"    async def test_create_{model_name.lower()}(self, async_client: AsyncClient):"
        )
        lines.append(f'        """Test creating a {model_name}."""')
        lines.append("        payload = {")
        lines.append("            # Add required fields here")
        lines.append("        }")
        lines.append("        response = await async_client.post(self.base_url, json=payload)")
        lines.append("        assert response.status_code in [200, 201]")
        lines.append("")

        # Test get
        lines.append("    @pytest.mark.asyncio")
        lines.append(
            f"    async def test_get_{model_name.lower()}(self, async_client: AsyncClient):"
        )
        lines.append(f'        """Test getting a single {model_name}."""')
        lines.append(f"        # Create a {model_name} first")
        lines.append(f"        item = await {model_name}.objects.acreate(")
        lines.append("            # Add required fields here")
        lines.append("        )")
        lines.append('        response = await async_client.get(f"{self.base_url}/{item.pk}")')
        lines.append("        assert response.status_code == 200")
        lines.append("")

        # Test update
        lines.append("    @pytest.mark.asyncio")
        lines.append(
            f"    async def test_update_{model_name.lower()}(self, async_client: AsyncClient):"
        )
        lines.append(f'        """Test updating a {model_name}."""')
        lines.append(f"        item = await {model_name}.objects.acreate(")
        lines.append("            # Add required fields here")
        lines.append("        )")
        lines.append("        payload = {")
        lines.append("            # Add fields to update")
        lines.append("        }")
        lines.append(
            '        response = await async_client.put(f"{self.base_url}/{item.pk}", json=payload)'
        )
        lines.append("        assert response.status_code == 200")
        lines.append("")

        # Test delete
        lines.append("    @pytest.mark.asyncio")
        lines.append(
            f"    async def test_delete_{model_name.lower()}(self, async_client: AsyncClient):"
        )
        lines.append(f'        """Test deleting a {model_name}."""')
        lines.append(f"        item = await {model_name}.objects.acreate(")
        lines.append("            # Add required fields here")
        lines.append("        )")
        lines.append('        response = await async_client.delete(f"{self.base_url}/{item.pk}")')
        lines.append("        assert response.status_code == 200")
        lines.append("")

        # Test not found
        lines.append("    @pytest.mark.asyncio")
        lines.append(
            f"    async def test_{model_name.lower()}_not_found(self, async_client: AsyncClient):"
        )
        lines.append(f'        """Test 404 for non-existent {model_name}."""')
        lines.append('        response = await async_client.get(f"{self.base_url}/99999")')
        lines.append("        assert response.status_code == 404")

        return "\n".join(lines)

    def _generate_service_content(self, context: dict) -> str:
        """Generate a service layer for business logic."""
        model_name = context["model_name"]
        app_label = context["app_label"]
        soft_delete = context["soft_delete"]
        fields = context["fields"]

        lines = []

        # Imports
        lines.append('"""')
        lines.append(f"Service layer for {model_name} business logic.")
        lines.append("")
        lines.append("This is where you write your business logic. Keep controllers thin -")
        lines.append("they should only handle HTTP concerns and delegate to services.")
        lines.append('"""')
        lines.append("")
        lines.append("from django.db import transaction")
        lines.append("from django.http import Http404")
        lines.append("")
        lines.append(f"from .models import {model_name}")
        lines.append(f"from .schemas import {model_name}CreateSchema, {model_name}UpdateSchema")
        lines.append("")
        lines.append("")

        # Service class
        lines.append(f"class {model_name}Service:")
        lines.append('    """')
        lines.append(f"    Service for {model_name} operations.")
        lines.append("")
        lines.append("    Add your business logic here:")
        lines.append("    - Validation beyond schema validation")
        lines.append("    - External service calls")
        lines.append("    - Complex transactions")
        lines.append("    - Event dispatching")
        lines.append("    - Notifications")
        lines.append('    """')
        lines.append("")

        # List method
        lines.append("    async def list(")
        lines.append("        self,")
        lines.append("        page: int = 1,")
        lines.append("        page_size: int = 20,")
        lines.append("        search: str | None = None,")
        lines.append("        **filters,")
        lines.append(f"    ) -> tuple[list[{model_name}], int]:")
        lines.append('        """')
        lines.append(f"        List {model_name} objects with optional filtering.")
        lines.append("")
        lines.append("        Returns:")
        lines.append("            Tuple of (items, total_count)")
        lines.append('        """')
        lines.append(f"        queryset = {model_name}.objects.all()")
        lines.append("")

        # Find searchable text fields from model
        from django.apps import apps as django_apps

        search_fields = []
        try:
            model_class = django_apps.get_model(app_label, model_name)
            for field in model_class._meta.get_fields():
                if hasattr(field, "get_internal_type"):
                    ft = field.get_internal_type()
                    if ft in ("CharField", "TextField") and field.name != "id":
                        search_fields.append(field.name)
        except LookupError:
            search_fields = []

        if search_fields:
            lines.append("        if search:")
            lines.append("            from django.db.models import Q")
            parts = " | ".join(
                f"Q({f}__icontains=search)" for f in search_fields[:3]
            )
            lines.append(f"            queryset = queryset.filter({parts})")
            lines.append("")

        lines.append("        for key, value in filters.items():")
        lines.append("            if value is not None:")
        lines.append("                queryset = queryset.filter(**{key: value})")
        lines.append("")
        lines.append("        total = await queryset.acount()")
        lines.append("        offset = (page - 1) * page_size")
        lines.append("        items = [item async for item in queryset[offset:offset + page_size]]")
        lines.append("")
        lines.append("        return items, total")
        lines.append("")

        # Get method
        lines.append(f"    async def get(self, id: int) -> {model_name}:")
        lines.append(f'        """Get a single {model_name} by ID."""')
        lines.append("        try:")
        lines.append(f"            return await {model_name}.objects.aget(pk=id)")
        lines.append(f"        except {model_name}.DoesNotExist:")
        lines.append(f'            raise Http404(f"{model_name} {{id}} not found")')
        lines.append("")

        # Create method
        lines.append("    async def create(")
        lines.append("        self,")
        lines.append(f"        data: {model_name}CreateSchema,")
        lines.append("        user=None,  # Optional: for created_by tracking")
        lines.append(f"    ) -> {model_name}:")
        lines.append('        """')
        lines.append(f"        Create a new {model_name}.")
        lines.append("")
        lines.append("        Args:")
        lines.append("            data: Creation data")
        lines.append("            user: Optional user for tracking created_by")
        lines.append('        """')
        lines.append("        create_data = data.model_dump()")
        lines.append("")
        lines.append("        if user:")
        lines.append("            create_data['created_by'] = user")
        lines.append("")
        lines.append(f"        item = await {model_name}.objects.acreate(**create_data)")
        lines.append("        return item")
        lines.append("")

        # Update method
        lines.append("    async def update(")
        lines.append("        self,")
        lines.append("        id: int,")
        lines.append(f"        data: {model_name}UpdateSchema,")
        lines.append("        partial: bool = False,")
        lines.append(f"    ) -> {model_name}:")
        lines.append('        """')
        lines.append(f"        Update a {model_name}.")
        lines.append("")
        lines.append("        Args:")
        lines.append("            id: The object ID")
        lines.append("            data: Update data")
        lines.append("            partial: If True, only update provided fields")
        lines.append('        """')
        lines.append("        item = await self.get(id)")
        lines.append("        update_data = data.model_dump(exclude_unset=partial)")
        lines.append("        for key, value in update_data.items():")
        lines.append("            setattr(item, key, value)")
        lines.append("        await item.asave()")
        lines.append("        return item")
        lines.append("")

        # Delete method
        lines.append("    async def delete(self, id: int) -> bool:")
        lines.append(f'        """Delete a {model_name}."""')
        lines.append("        item = await self.get(id)")
        lines.append("")

        if soft_delete:
            lines.append("        # Soft delete")
            lines.append("        item.is_deleted = True")
            lines.append("        await item.asave()")
        else:
            lines.append("        await item.adelete()")

        lines.append("        return True")
        lines.append("")

        # Example custom methods
        lines.append("    # =========================================")
        lines.append("    # Add your custom business methods below")
        lines.append("    # =========================================")
        lines.append("")
        lines.append(f"    # async def activate(self, id: int) -> {model_name}:")
        lines.append(f'    #     """Example: Activate a {model_name}."""')
        lines.append("    #     item = await self.get(id)")
        lines.append("    #     item.is_active = True")
        lines.append("    #     await item.asave()")
        lines.append("    #     # Send activation email, dispatch event, etc.")
        lines.append("    #     return item")
        lines.append("")
        lines.append(
            f"    # async def bulk_create(self, items: list[{model_name}CreateSchema]) -> list[{model_name}]:"
        )
        lines.append(f'    #     """Example: Bulk create {model_name} objects."""')
        lines.append("    #     async with transaction.atomic():")
        lines.append(f"    #         return await {model_name}.objects.abulk_create([")
        lines.append(f"    #             {model_name}(**item.model_dump()) for item in items")
        lines.append("    #         ])")

        return "\n".join(lines)

    def _generate_admin_content(self, context: dict) -> str:
        """Generate Django Unfold admin configuration."""
        model_name = context["model_name"]
        app_label = context["app_label"]
        fields = context["fields"]
        soft_delete = context["soft_delete"]

        lines = []

        # Imports
        lines.append('"""')
        lines.append(f"Django Unfold admin configuration for {model_name}.")
        lines.append("")
        lines.append("This admin is configured to work with Django Unfold's design system.")
        lines.append("Make sure you have 'unfold' in INSTALLED_APPS before 'django.contrib.admin'.")
        lines.append('"""')
        lines.append("")
        lines.append("from django.contrib import admin")
        lines.append("")
        lines.append("from django_matt.admin import (")
        lines.append("    MattModelAdmin,")
        lines.append("    register_admin,")

        if soft_delete:
            lines.append("    SoftDeleteAdminMixin,")

        lines.append("    export_as_csv,")
        lines.append("    export_as_json,")
        lines.append(")")
        lines.append("")
        lines.append(f"from .models import {model_name}")
        lines.append("")
        lines.append("")

        # Determine list_display, list_filter, search_fields from model fields
        list_display = ["id"]
        list_filter = []
        search_fields = []
        readonly_fields = []

        for field in fields:
            name = field["name"]
            ftype = field["type"]

            # Skip certain fields
            if name in ("id", "pk"):
                continue

            # Add to list_display (limit to reasonable number)
            if len(list_display) < 7:
                if field["is_relation"] or ftype in (
                    "str",
                    "int",
                    "float",
                    "bool",
                    "date",
                    "datetime",
                ):
                    list_display.append(name)

            # Add filterable fields
            if (
                ftype == "bool"
                or field["is_relation"]
                or (ftype in ("date", "datetime") and len(list_filter) < 5)
            ):
                list_filter.append(name)

            # Add searchable fields
            if ftype == "str" and not field["is_relation"]:
                search_fields.append(name)

            # Auto timestamps are readonly
            if name in ("created_at", "updated_at", "created", "modified"):
                readonly_fields.append(name)

        # Build admin class
        if soft_delete:
            lines.append(f"@register_admin({model_name})")
            lines.append(f"class {model_name}Admin(SoftDeleteAdminMixin, MattModelAdmin):")
        else:
            lines.append(f"@register_admin({model_name})")
            lines.append(f"class {model_name}Admin(MattModelAdmin):")

        lines.append(f'    """Admin configuration for {model_name}."""')
        lines.append("")

        # List display
        list_display_str = ", ".join(f'"{f}"' for f in list_display)
        lines.append(f"    list_display = [{list_display_str}]")

        # List filter
        if list_filter:
            list_filter_str = ", ".join(f'"{f}"' for f in list_filter)
            lines.append(f"    list_filter = [{list_filter_str}]")

        # Search fields
        if search_fields:
            search_fields_str = ", ".join(f'"{f}"' for f in search_fields)
            lines.append(f"    search_fields = [{search_fields_str}]")

        # Readonly fields
        if readonly_fields:
            readonly_fields_str = ", ".join(f'"{f}"' for f in readonly_fields)
            lines.append(f"    readonly_fields = [{readonly_fields_str}]")

        # Ordering
        lines.append('    ordering = ["-id"]')

        # Pagination
        lines.append("    list_per_page = 25")

        lines.append("")

        # Actions
        lines.append("    # Export actions")
        lines.append("    actions = [export_as_csv, export_as_json]")
        lines.append("")

        # Fieldsets - organize fields into logical groups
        lines.append("    # Uncomment and customize fieldsets for better organization")
        lines.append("    # fieldsets = (")
        lines.append("    #     (None, {")
        lines.append('    #         "fields": ("field1", "field2"),')
        lines.append("    #     }),")
        lines.append('    #     ("Details", {')
        lines.append('    #         "fields": ("field3", "field4"),')
        lines.append('    #         "classes": ("collapse",),  # Collapsible section')
        lines.append("    #     }),")

        if readonly_fields:
            lines.append('    #     ("Timestamps", {')
            readonly_str = ", ".join(f'"{f}"' for f in readonly_fields)
            lines.append(f'    #         "fields": ({readonly_str},),')
            lines.append('    #         "classes": ("collapse",),')
            lines.append("    #     }),")

        lines.append("    # )")
        lines.append("")

        # Custom methods example
        lines.append("    # =========================================")
        lines.append("    # Custom admin methods")
        lines.append("    # =========================================")
        lines.append("")
        lines.append("    # def get_queryset(self, request):")
        lines.append('    #     """Customize the queryset (e.g., for multi-tenant filtering)."""')
        lines.append("    #     qs = super().get_queryset(request)")
        lines.append("    #     # Example: Filter by user's organization")
        lines.append("    #     # if not request.user.is_superuser:")
        lines.append("    #     #     qs = qs.filter(organization=request.user.organization)")
        lines.append("    #     return qs")
        lines.append("")
        lines.append("    # def save_model(self, request, obj, form, change):")
        lines.append('    #     """Add custom logic when saving."""')
        lines.append("    #     if not change:  # Creating new object")
        lines.append("    #         obj.created_by = request.user")
        lines.append("    #     super().save_model(request, obj, form, change)")

        return "\n".join(lines)
