"""
Django settings for {{ project_name }}.

Generated by django-matt startapi (api-only template).
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "change-me-in-production")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS: list[str] = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django_matt",
    "{{ project_name }}_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_matt.core.errors.ErrorMiddleware",
    "django_matt.multitenancy.TenantMiddlewareAsync",
    "django_matt.observability.ObservabilityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES: list[dict] = []

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{ project_name }}"),
        "USER": os.environ.get("POSTGRES_USER", "{{ project_name }}"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "{{ project_name }}"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = False
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS: list[str] = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")

# Django Matt — JWT
DJANGO_MATT_JWT = {
    "SECRET_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": 60 * 15,
    "REFRESH_TOKEN_LIFETIME": 60 * 60 * 24 * 7,
    "ALGORITHM": "HS256",
}
