# Generated by Django 6.0.5 on 2026-05-19 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("long_description", models.TextField(blank=True)),
                ("tech_stack", models.JSONField(default=list)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
