"""
Django settings for {{ project_name }}.

Generated by django-matt startapi (marketplace template).
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "change-me-in-production")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS: list[str] = os.environ.get("ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django_matt",
    "{{ project_name }}_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_matt.core.errors.ErrorMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES: list[dict] = []

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{ project_name }}"),
        "USER": os.environ.get("POSTGRES_USER", "{{ project_name }}"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "{{ project_name }}"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = False
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS: list[str] = os.environ.get(
    "CORS_ALLOWED_ORIGINS", ""
).split(",")

# Django Matt — JWT
DJANGO_MATT_JWT = {
    "SECRET_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": 60 * 15,
    "REFRESH_TOKEN_LIFETIME": 60 * 60 * 24 * 7,
    "ALGORITHM": "HS256",
}

# Redis cache (search, sessions, rate limiting)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://localhost:6379/0"),
    }
}

# Multitenancy — organizations as vendors
DJANGO_MATT_MULTITENANCY = {
    "ENABLED": True,
    "TENANT_HEADER": "X-Store-ID",
    "TENANT_URL_KWARG": "store_slug",
    "REQUIRE_TENANT": False,
    "EXEMPT_PATHS": ["/auth/", "/health/", "/docs/", "/search/"],
}

# Billing — Stripe Connect for marketplace payouts
DJANGO_MATT_BILLING = {
    "PROVIDER": "stripe",
    "STRIPE_SECRET_KEY": os.environ.get("STRIPE_SECRET_KEY", ""),
    "STRIPE_WEBHOOK_SECRET": os.environ.get("STRIPE_WEBHOOK_SECRET", ""),
    "CONNECT_ENABLED": True,
    "PLATFORM_FEE_PERCENT": 10,
}

# File uploads
DJANGO_MATT_FILES = {
    "BACKEND": "local",  # switch to "s3" or "r2" in production
    "UPLOAD_DIR": BASE_DIR / "uploads",
    "MAX_SIZE_MB": 10,
    "ALLOWED_TYPES": ["image/jpeg", "image/png", "image/webp"],
}
