"""
Django settings for {{ project_name }}.

Generated by django-matt startapi (ai-saas template).
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "change-me-in-production")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS: list[str] = os.environ.get("ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django_matt",
    "{{ project_name }}_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_matt.core.errors.ErrorMiddleware",
    "django_matt.multitenancy.TenantMiddlewareAsync",
    "django_matt.observability.ObservabilityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES: list[dict] = []

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{ project_name }}"),
        "USER": os.environ.get("POSTGRES_USER", "{{ project_name }}"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "{{ project_name }}"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = False
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS: list[str] = os.environ.get(
    "CORS_ALLOWED_ORIGINS", ""
).split(",")

# Django Matt — JWT
DJANGO_MATT_JWT = {
    "SECRET_KEY": SECRET_KEY,
    "ACCESS_TOKEN_LIFETIME": 60 * 15,
    "REFRESH_TOKEN_LIFETIME": 60 * 60 * 24 * 7,
    "ALGORITHM": "HS256",
}

# Redis cache (rate limiting, sessions, task results)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://localhost:6379/0"),
    }
}

# Billing — Stripe
DJANGO_MATT_BILLING = {
    "PROVIDER": "stripe",
    "STRIPE_SECRET_KEY": os.environ.get("STRIPE_SECRET_KEY", ""),
    "STRIPE_WEBHOOK_SECRET": os.environ.get("STRIPE_WEBHOOK_SECRET", ""),
    "METERED_BILLING": True,
}

# Rate limiting per billing tier
DJANGO_MATT_THROTTLE = {
    "DEFAULT": "100/hour",
    "TIERS": {
        "free": "20/hour",
        "pro": "200/hour",
        "enterprise": "2000/hour",
    },
}

# AI / LLM configuration
DJANGO_MATT_AI = {
    "DEFAULT_PROVIDER": "anthropic",
    "ANTHROPIC_API_KEY": os.environ.get("ANTHROPIC_API_KEY", ""),
    "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", ""),
    "EMBEDDING_MODEL": "text-embedding-3-small",
    "EMBEDDING_DIMENSIONS": 1536,
    "MAX_TOKENS": 4096,
    "STREAMING": True,
}

# Vector storage for RAG
DJANGO_MATT_VECTOR = {
    "BACKEND": "pgvector",
    "DISTANCE_METRIC": "cosine",
}

# SSE streaming
DJANGO_MATT_STREAMING = {
    "SSE_ENABLED": True,
    "HEARTBEAT_INTERVAL": 15,
}

# Background tasks
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/2")

# WebSocket
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379/3")],
        },
    },
}
