"""
Templates for AI context file generation.

Provides customizable templates for CLAUDE.md, .cursorrules,
.copilot-instructions, and other AI assistant context files.
"""

from datetime import datetime
from typing import Any

# =============================================================================
# CLAUDE.md Template
# =============================================================================

CLAUDE_MD_TEMPLATE = """# {project_name} - AI Assistant Context

> Auto-generated by django-matt on {generated_date}
> This file provides context for AI assistants (Claude, Cursor, Copilot, etc.)

## Project Overview

- **Name**: {project_name}
- **Type**: Django Application with django-matt framework
- **Python**: {python_version}
- **Django**: {django_version}
- **Settings**: `{settings_module}`

{tech_stack_section}

{structure_section}

{models_section}

{endpoints_section}

{schemas_section}

{auth_section}

{async_safety_section}

{error_handling_section}

{service_layer_section}

{environment_section}

{test_patterns_section}

{code_examples_section}

## Coding Conventions

### Python Style
- Follow PEP 8 with 88-character line limit (Black formatter)
- Use type hints for function signatures
- Prefer `async def` for views when possible
- Use Pydantic for all request/response validation

### Django Matt Patterns
- Use `@api.get`, `@api.post` decorators for API endpoints
- Use `APIController` for class-based API logic
- Use `ModelSchema` for Django model serialization
- Return `JsonResponse` with appropriate status codes

### Authentication
- Use `@jwt_required` for protected endpoints
- Use `@jwt_optional` for optionally authenticated endpoints
- Access user via `request.user` after authentication
- Use permission classes: `IsAuthenticated`, `IsAdmin`, `HasRole`

### Database
- Use `select_related` and `prefetch_related` to avoid N+1
- Use `F()` expressions for atomic updates
- Use `transaction.atomic()` for multiple related operations
- Prefer async ORM methods (`aget`, `afilter`, `acreate`)

### Error Handling
- Raise `ValidationAPIError` for validation failures
- Raise `NotFoundAPIError` for missing resources
- Use `APIError` base class for custom errors

## Common Commands

```bash
# Development
python manage.py runserver
python manage.py migrate
python manage.py makemigrations

# Testing
pytest
pytest tests/ -v
pytest --cov=.

# Code Quality
ruff check .
ruff format .
mypy .

# AI Context
python manage.py generate_ai_context
python manage.py generate_ai_context --watch
```

## Important Files

{important_files}
"""


# =============================================================================
# Cursor Rules Template
# =============================================================================

CURSOR_RULES_TEMPLATE = """# {project_name} - Cursor Rules
# Django {django_version} with Python {python_version}
# Auto-generated by django-matt on {generated_date}

## Framework Rules

# API Development
- Use `@api.get`, `@api.post` decorators for endpoints
- Use Pydantic schemas for request/response validation
- Use `async def` for database operations
- Return `JsonResponse` with appropriate status codes

# Controllers
- Extend `APIController` for class-based endpoints
- Set `prefix` and `tags` class attributes
- Use dependency injection via type hints

# Models
- Define `__str__` method for all models
- Use `related_name` for ForeignKey relationships
- Add `class Meta` with `ordering` and `verbose_name`

# Authentication
- Use `@jwt_required` for protected endpoints
- Access user via `request.user`
- Use `IsAuthenticated`, `IsAdmin` permission classes

# Database
- Use `select_related` and `prefetch_related`
- Use `F()` expressions for atomic updates
- Prefer async ORM methods

# Error Handling
- Raise `ValidationAPIError` for validation failures
- Raise `NotFoundAPIError` for missing resources

{models_rules}

{endpoints_rules}

{schema_rules}

{async_safety_rules}

## Import Preferences

# Core imports
from django_matt import MattAPI
from django_matt.core import APIController, ModelSchema
from django_matt.auth import jwt_required, IsAuthenticated
from django_matt.views import ListView, CreateView, ReadView
from pydantic import BaseModel, Field

# Testing imports
import pytest
from django_matt.testing import APITestClient
"""


# =============================================================================
# Copilot Instructions Template
# =============================================================================

COPILOT_INSTRUCTIONS_TEMPLATE = """# GitHub Copilot Instructions for {project_name}

## Project Context
This is a Django {django_version} application using the django-matt framework.
Python version: {python_version}

## Code Style Guidelines

### API Endpoints
When writing API endpoints:
1. Use `@api.get`, `@api.post`, etc. decorators from django_matt
2. Always use Pydantic schemas for request/response
3. Prefer async functions with `async def`
4. Return `JsonResponse` with proper status codes

Example:
```python
from django_matt import MattAPI
from django_matt.auth import jwt_required
from django.http import JsonResponse

api = MattAPI()

@api.get("/items")
@jwt_required
async def list_items(request):
    items = await Item.objects.all()
    return JsonResponse({{"items": [i.to_dict() for i in items]}})
```

### Controllers
When writing controllers:
1. Extend `APIController`
2. Set `prefix` and `tags` class attributes
3. Use Pydantic models for input validation

Example:
```python
from django_matt.core import APIController
from django_matt.core.router import get, post

class ItemController(APIController):
    prefix = "items"
    tags = ["Items"]

    @get("")
    async def list(self, request):
        return await Item.objects.all()
```

### Pydantic Schemas
When writing schemas:
1. Extend `BaseModel` from pydantic
2. Use `Field()` for validation constraints
3. Include docstrings for documentation

Example:
```python
from pydantic import BaseModel, Field

class CreateItemRequest(BaseModel):
    \"\"\"Request schema for creating an item.\"\"\"
    name: str = Field(..., min_length=1, max_length=255)
    price: float = Field(..., gt=0)
    description: str | None = None
```

{models_context}

{endpoints_context}

{schemas_context}

{async_patterns_context}

{error_handling_context}

## Authentication Patterns
- `@jwt_required` - Requires valid JWT token
- `@jwt_optional` - Token optional, sets request.user if present
- `IsAuthenticated` - Permission class for authenticated users
- `IsAdmin` - Permission class for admin users

## Testing Patterns
- Use `pytest` with `pytest-django`
- Use `APITestClient` from django_matt.testing
- Use factories for test data

## Common Imports
```python
# API
from django_matt import MattAPI
from django_matt.core import APIController, ModelSchema
from django_matt.core.router import get, post, put, patch, delete

# Auth
from django_matt.auth import jwt_required, jwt_optional
from django_matt.permissions import IsAuthenticated, IsAdmin

# Schemas
from pydantic import BaseModel, Field

# Testing
import pytest
from django_matt.testing import APITestClient
```
"""


# =============================================================================
# Template Rendering Functions
# =============================================================================


def get_template(template_name: str) -> str:
    """
    Get a template by name.

    Args:
        template_name: One of 'claude', 'cursor', 'copilot'

    Returns:
        Template string
    """
    templates = {
        "claude": CLAUDE_MD_TEMPLATE,
        "cursor": CURSOR_RULES_TEMPLATE,
        "copilot": COPILOT_INSTRUCTIONS_TEMPLATE,
        "llm": LLM_SYSTEM_PROMPT_TEMPLATE,
    }

    if template_name not in templates:
        raise ValueError(f"Unknown template: {template_name}. Available: {list(templates.keys())}")

    return templates[template_name]


def render_template(template: str, context: dict[str, Any]) -> str:
    """
    Render a template with the given context.

    Uses simple string formatting with fallbacks for missing keys.

    Args:
        template: Template string with {key} placeholders
        context: Dictionary of values to substitute

    Returns:
        Rendered template string
    """
    # Add defaults for common fields
    defaults = {
        "generated_date": datetime.now().strftime("%Y-%m-%d"),
        "project_name": "Django Project",
        "python_version": "3.12",
        "django_version": "5.0",
        "settings_module": "",
        "tech_stack_section": "",
        "structure_section": "",
        "models_section": "",
        "endpoints_section": "",
        "schemas_section": "",
        "auth_section": "",
        "async_safety_section": "",
        "error_handling_section": "",
        "service_layer_section": "",
        "environment_section": "",
        "test_patterns_section": "",
        "code_examples_section": "",
        "important_files": "",
        "models_rules": "",
        "endpoints_rules": "",
        "schema_rules": "",
        "async_safety_rules": "",
        "models_context": "",
        "endpoints_context": "",
        "schemas_context": "",
        "async_patterns_context": "",
        "error_handling_context": "",
    }

    # Merge defaults with provided context
    full_context = {**defaults, **context}

    # Perform substitution
    try:
        return template.format(**full_context)
    except KeyError as e:
        # If a key is missing, try with empty string
        missing_key = str(e).strip("'")
        full_context[missing_key] = ""
        return template.format(**full_context)


def format_tech_stack(info: dict[str, Any]) -> str:
    """Format tech stack section."""
    lines = ["## Tech Stack", ""]
    lines.append(f"- **Python**: {info.get('python_version', '3.12')}")
    lines.append(f"- **Django**: {info.get('django_version', '5.0')}")

    databases = info.get("databases", {})
    for name, engine in databases.items():
        lines.append(f"- **Database ({name})**: {engine}")

    return "\n".join(lines)


def format_models_section(models: list[dict[str, Any]], max_models: int = 20) -> str:
    """Format models section for CLAUDE.md."""
    if not models:
        return ""

    lines = ["## Data Models", ""]

    for model in models[:max_models]:
        lines.append(f"### `{model['app_label']}.{model['name']}`")
        if model.get("docstring"):
            lines.append(f"_{model['docstring'].split(chr(10))[0]}_")
        lines.append("")

        lines.append("| Field | Type | Notes |")
        lines.append("|-------|------|-------|")

        for field in model.get("fields", [])[:15]:
            notes = []
            if field.get("primary_key"):
                notes.append("PK")
            if field.get("unique"):
                notes.append("unique")
            if field.get("nullable"):
                notes.append("nullable")
            if field.get("related_to"):
                notes.append(f"-> {field['related_to']}")

            lines.append(f"| `{field['name']}` | {field['type']} | {', '.join(notes) or '-'} |")

        lines.append("")

    if len(models) > max_models:
        lines.append(f"_... and {len(models) - max_models} more models_")

    return "\n".join(lines)


def format_endpoints_section(endpoints: list[dict[str, Any]], max_endpoints: int = 30) -> str:
    """Format endpoints section for CLAUDE.md."""
    if not endpoints:
        return ""

    lines = ["## API Endpoints", ""]
    lines.append("| Method | Path | Auth | Description |")
    lines.append("|--------|------|------|-------------|")

    for ep in endpoints[:max_endpoints]:
        auth = ep.get("auth_requirement", "none")
        auth_badge = {
            "none": "-",
            "jwt_required": "JWT",
            "jwt_optional": "JWT?",
            "api_key": "API Key",
            "session": "Session",
        }.get(auth, auth)

        desc = ep.get("docstring", "")[:50]
        if len(ep.get("docstring", "")) > 50:
            desc += "..."

        lines.append(f"| `{ep['method']}` | `{ep['path']}` | {auth_badge} | {desc} |")

    if len(endpoints) > max_endpoints:
        lines.append(f"| ... | | | +{len(endpoints) - max_endpoints} more |")

    return "\n".join(lines)


def format_schemas_section(schemas: list[dict[str, Any]], max_schemas: int = 20) -> str:
    """Format schemas section for CLAUDE.md."""
    if not schemas:
        return ""

    lines = ["## Pydantic Schemas", ""]

    for schema in schemas[:max_schemas]:
        lines.append(f"### `{schema['name']}`")
        if schema.get("docstring"):
            lines.append(f"_{schema['docstring'].split(chr(10))[0]}_")
        if schema.get("django_model"):
            lines.append(f"_ModelSchema for {schema['django_model']}_")
        lines.append("")

        if schema.get("fields"):
            lines.append("| Field | Type | Required |")
            lines.append("|-------|------|----------|")

            for field in schema["fields"][:10]:
                req = "Yes" if field.get("required", True) else "No"
                lines.append(f"| `{field['name']}` | `{field['type']}` | {req} |")

            if len(schema["fields"]) > 10:
                lines.append(f"| ... | | +{len(schema['fields']) - 10} more |")

        lines.append("")

    return "\n".join(lines)


def format_auth_section(endpoints: list[dict[str, Any]]) -> str:
    """Format authentication section."""
    # Group endpoints by auth requirement
    auth_groups: dict[str, list[str]] = {}
    for ep in endpoints:
        auth = ep.get("auth_requirement", "none")
        if auth not in auth_groups:
            auth_groups[auth] = []
        auth_groups[auth].append(f"`{ep['method']} {ep['path']}`")

    if not auth_groups or (len(auth_groups) == 1 and "none" in auth_groups):
        return ""

    lines = ["## Authentication Requirements", ""]

    auth_labels = {
        "jwt_required": "JWT Required",
        "jwt_optional": "JWT Optional",
        "api_key": "API Key Required",
        "session": "Session Required",
        "permission_required": "Permission Required",
        "role_required": "Role Required",
        "none": "Public (No Auth)",
    }

    for auth_type, endpoints_list in auth_groups.items():
        label = auth_labels.get(auth_type, auth_type)
        lines.append(f"### {label}")
        for ep in endpoints_list[:10]:
            lines.append(f"- {ep}")
        if len(endpoints_list) > 10:
            lines.append(f"- ... and {len(endpoints_list) - 10} more")
        lines.append("")

    return "\n".join(lines)


def format_test_patterns_section(test_patterns: dict[str, Any] | None) -> str:
    """Format test patterns section."""
    if not test_patterns:
        return ""

    lines = ["## Test Patterns", ""]
    lines.append(f"- **Framework**: {test_patterns.get('framework', 'pytest')}")

    if test_patterns.get("fixture_files"):
        lines.append("- **Fixture Files**:")
        for f in test_patterns["fixture_files"][:5]:
            lines.append(f"  - `{f}`")

    if test_patterns.get("factory_files"):
        lines.append("- **Factory Files**:")
        for f in test_patterns["factory_files"][:5]:
            lines.append(f"  - `{f}`")

    if test_patterns.get("common_patterns"):
        lines.append("- **Patterns**:")
        for p in test_patterns["common_patterns"]:
            lines.append(f"  - {p}")

    return "\n".join(lines)


def format_code_examples_section(
    examples: dict[str, list[dict[str, str]]], max_per_category: int = 2
) -> str:
    """Format code examples section."""
    if not examples:
        return ""

    lines = ["## Code Examples from Codebase", ""]

    category_labels = {
        "controllers": "Controller Examples",
        "views": "View Examples",
        "schemas": "Schema Examples",
        "models": "Model Examples",
        "tests": "Test Examples",
    }

    for category, example_list in examples.items():
        if not example_list:
            continue

        lines.append(f"### {category_labels.get(category, category)}")
        lines.append("")

        for ex in example_list[:max_per_category]:
            lines.append(f"From `{ex.get('file', 'unknown')}` (line {ex.get('line', '?')}):")
            lines.append("```python")
            lines.append(ex.get("code", ""))
            lines.append("```")
            lines.append("")

    return "\n".join(lines)


def format_models_rules(models: list[dict[str, Any]]) -> str:
    """Format model rules for Cursor."""
    if not models:
        return ""

    lines = ["## Project Models", ""]
    lines.append("# Available models:")

    for model in models[:20]:
        field_count = len(model.get("fields", []))
        lines.append(f"- `{model['app_label']}.{model['name']}`: {field_count} fields")

    if len(models) > 20:
        lines.append(f"- ... and {len(models) - 20} more")

    return "\n".join(lines)


def format_endpoints_rules(endpoints: list[dict[str, Any]]) -> str:
    """Format endpoint rules for Cursor."""
    if not endpoints:
        return ""

    lines = ["## API Endpoints", ""]
    lines.append("# Available endpoints:")

    for ep in endpoints[:30]:
        auth = ep.get("auth_requirement", "none")
        auth_mark = "[AUTH]" if auth not in ("none", "unknown") else ""
        lines.append(f"- {ep['method']} {ep['path']} {auth_mark}")

    if len(endpoints) > 30:
        lines.append(f"- ... and {len(endpoints) - 30} more")

    return "\n".join(lines)


def format_schema_rules(schemas: list[dict[str, Any]]) -> str:
    """Format schema rules for Cursor."""
    if not schemas:
        return ""

    lines = ["## Pydantic Schemas", ""]
    lines.append("# Available schemas:")

    for schema in schemas[:20]:
        field_count = len(schema.get("fields", []))
        model_info = (
            f" (ModelSchema for {schema['django_model']})" if schema.get("django_model") else ""
        )
        lines.append(f"- `{schema['name']}`: {field_count} fields{model_info}")

    if len(schemas) > 20:
        lines.append(f"- ... and {len(schemas) - 20} more")

    return "\n".join(lines)


def format_async_safety_section(
    async_warnings: list[dict[str, Any]],
    endpoints: list[dict[str, Any]],
) -> str:
    """Format async safety section for CLAUDE.md."""
    has_async = any(
        ep.get("view_name", "").startswith("async") or ep.get("method", "") != ""
        for ep in endpoints
    )

    lines = ["## Async Safety Guide", ""]
    lines.append("### Rules")
    lines.append("- **NEVER** use sync ORM methods in async views/functions")
    lines.append("- Use async ORM methods: `.aget()`, `.afilter()`, `.acreate()`, `.asave()`, `.adelete()`")
    lines.append("- For sync code in async context, wrap with `sync_to_async()`")
    lines.append("")
    lines.append("### Correct vs Incorrect")
    lines.append("```python")
    lines.append("# WRONG - blocks the event loop")
    lines.append("async def get_user(request, pk):")
    lines.append("    user = User.objects.get(pk=pk)  # sync call in async!")
    lines.append("")
    lines.append("# CORRECT - async ORM method")
    lines.append("async def get_user(request, pk):")
    lines.append("    user = await User.objects.aget(pk=pk)")
    lines.append("")
    lines.append("# CORRECT - sync_to_async wrapper")
    lines.append("from asgiref.sync import sync_to_async")
    lines.append("async def get_user(request, pk):")
    lines.append("    user = await sync_to_async(User.objects.get)(pk=pk)")
    lines.append("```")

    if async_warnings:
        lines.append("")
        lines.append(f"### Current Issues ({len(async_warnings)} detected)")
        for w in async_warnings[:10]:
            lines.append(f"- `{w['file']}:{w['line']}` in `{w['function']}`: {w['issue']}")

    return "\n".join(lines)


def format_error_handling_section(project_info: dict[str, Any]) -> str:
    """Format error handling section for CLAUDE.md."""
    lines = ["## Error Handling", ""]
    lines.append("### Framework Error Classes")
    lines.append("```python")
    lines.append("from django_matt.core.errors import (")
    lines.append("    APIError,              # Base error (status, message, code)")
    lines.append("    ValidationAPIError,    # 400 - validation failures")
    lines.append("    AuthenticationError,   # 401 - not authenticated")
    lines.append("    PermissionError,       # 403 - not authorized")
    lines.append("    NotFoundAPIError,      # 404 - resource not found")
    lines.append("    ConflictAPIError,      # 409 - resource conflict")
    lines.append("    RateLimitError,        # 429 - rate limited")
    lines.append(")")
    lines.append("```")
    lines.append("")
    lines.append("### Usage Patterns")
    lines.append("```python")
    lines.append("# Raise specific errors — framework handles JSON response")
    lines.append("raise NotFoundAPIError(f'User {pk} not found')")
    lines.append("raise ValidationAPIError('Email is required', field='email')")
    lines.append("")
    lines.append("# Custom errors")
    lines.append("raise APIError(status=402, message='Payment required', code='payment_required')")
    lines.append("```")

    return "\n".join(lines)


def format_service_layer_section(services: list[dict[str, Any]]) -> str:
    """Format service layer section for CLAUDE.md."""
    if not services:
        return ""

    lines = ["## Service Layer", ""]
    lines.append("Detected service classes in the project:")
    lines.append("")

    for svc in services[:15]:
        async_badge = " (async)" if svc.get("is_async") else ""
        lines.append(f"### `{svc['name']}`{async_badge}")
        if svc.get("docstring"):
            lines.append(f"_{svc['docstring'].split(chr(10))[0]}_")
        lines.append(f"Module: `{svc['module']}`")
        lines.append("")

        if svc.get("methods"):
            for method in svc["methods"][:8]:
                async_prefix = "async " if method.get("is_async") else ""
                params_str = ", ".join(p["name"] for p in method.get("params", []))
                ret = f" -> {method['return_type']}" if method.get("return_type") else ""
                lines.append(f"- `{async_prefix}{method['name']}({params_str}){ret}`")
            if len(svc["methods"]) > 8:
                lines.append(f"- ... and {len(svc['methods']) - 8} more methods")
        lines.append("")

    return "\n".join(lines)


def format_environment_section(environment: list[dict[str, Any]]) -> str:
    """Format environment variables section for CLAUDE.md."""
    if not environment:
        return ""

    lines = ["## Environment Variables", ""]

    required = [e for e in environment if e.get("required", True)]
    optional = [e for e in environment if not e.get("required", True)]

    if required:
        lines.append("### Required")
        lines.append("| Variable | Source |")
        lines.append("|----------|--------|")
        for var in required[:20]:
            lines.append(f"| `{var['name']}` | `{var.get('source_file', '')}` |")
        lines.append("")

    if optional:
        lines.append("### Optional (with defaults)")
        lines.append("| Variable | Default | Source |")
        lines.append("|----------|---------|--------|")
        for var in optional[:20]:
            default = var.get("default", "")
            if default and len(str(default)) > 30:
                default = str(default)[:27] + "..."
            lines.append(f"| `{var['name']}` | `{default}` | `{var.get('source_file', '')}` |")
        lines.append("")

    return "\n".join(lines)


def format_async_safety_rules(async_warnings: list[dict[str, Any]]) -> str:
    """Format async safety rules for Cursor."""
    lines = ["## Async Safety", ""]
    lines.append("# CRITICAL: Never use sync ORM in async views")
    lines.append("- .get() -> .aget()")
    lines.append("- .filter() -> .afilter()")
    lines.append("- .create() -> .acreate()")
    lines.append("- .save() -> .asave()")
    lines.append("- .delete() -> .adelete()")
    lines.append("- .all() -> .aall()")
    lines.append("- .first() -> .afirst()")
    lines.append("- .exists() -> .aexists()")
    lines.append("- .count() -> .acount()")
    lines.append("- Or wrap with sync_to_async()")

    if async_warnings:
        lines.append("")
        lines.append(f"# WARNING: {len(async_warnings)} async safety issue(s) detected in codebase")

    return "\n".join(lines)


# =============================================================================
# LLM System Prompt Template
# =============================================================================

LLM_SYSTEM_PROMPT_TEMPLATE = """You are an expert Django Matt developer. Django Matt is a standalone Django meta-framework that replaces Django REST Framework, Django Ninja, and their ecosystems with one cohesive, async-first library built on Pydantic v2.

## Core Truths (violating these produces broken code)

1. Async-first — all controllers/views use `async def`. All ORM calls use async variants (.aget(), .acreate(), .asave(), .adelete(), .aexists(), .acount(), .afirst()). QuerySets are NOT awaitable — iterate with `[x async for x in qs]`.
2. Pydantic v2, not DRF — `ModelSchema` and `Schema`, never `ModelSerializer`.
3. orjson is always available — base dependency. `import orjson` directly. Never conditional.
4. Built-in JWT — no PyJWT dependency. Use `django_matt.auth.jwt_builtin`.
5. uv, not pip — `uv add django-matt`.
6. register_controller() takes ONE argument — the class. No prefix. Prefix comes from `@api.controller("/prefix")`.
7. Python 3.12+ / Django 5.2+ — use `str | None`, `list[int]`, `dict[str, Any]`.

## Project: {project_name}

- Python {python_version} / Django {django_version}
- Settings: `{settings_module}`

{models_section}

{endpoints_section}

{schemas_section}

{auth_section}

## Async Safety — CRITICAL

- NEVER use sync ORM in async context: .get() → .aget(), .save() → .asave(), .delete() → .adelete()
- QuerySets are NOT awaitable: `[x async for x in qs]`
- NEVER use `import requests` in async — use `httpx.AsyncClient()`
- Wrap sync-only code with `sync_to_async()`

{async_safety_section}

## Error Handling

```python
from django_matt.core.errors import (
    APIError,              # Base — any status code
    ValidationAPIError,    # 400
    NotFoundAPIError,      # 404
    PermissionAPIError,    # 403
)
raise NotFoundAPIError(message="Resource not found")
raise ValidationAPIError(message="Invalid data", field="email")
```

## Key Imports

```python
from django_matt import MattAPI, APIController, get, post, put, patch, delete
from django_matt import ModelSchema, Schema
from django_matt.views import APIViewSet, ListView, CreateView, ReadView, UpdateView, DeleteView
from django_matt.auth import jwt_required, jwt_optional, create_token_pair, with_roles
from django_matt.permissions import IsAuthenticated, IsAdmin, IsOwner, HasRole
from django_matt.core.errors import APIError, NotFoundAPIError, ValidationAPIError
from django_matt.di import Depends
import orjson
```

## Anti-Patterns — NEVER Do These

- `api.register_controller(Ctrl, prefix="/x")` → `api.register_controller(Ctrl)` (prefix from decorator)
- `await User.objects.all()` → `[u async for u in User.objects.all()]`
- `user.save()` → `await user.asave()`
- `import json` → `import orjson`
- `import jwt` → `from django_matt.auth.jwt_builtin import encode_jwt`
- `from rest_framework import serializers` → `from django_matt import ModelSchema`
- Caching get_type_hints() per-request → cache at init time
- Loop closure capture without default arg binding

{service_layer_section}

{environment_section}

{test_patterns_section}
"""


def format_llm_prompt(
    project_info: dict[str, Any],
    models: list[dict[str, Any]],
    endpoints: list[dict[str, Any]],
    schemas: list[dict[str, Any]],
    async_warnings: list[dict[str, Any]],
    services: list[dict[str, Any]],
    environment: list[dict[str, Any]],
    test_patterns: dict[str, Any] | None = None,
) -> str:
    """
    Render the LLM system prompt template with project-specific data.

    This produces a self-contained system prompt that any LLM can consume
    to generate correct django-matt code for a specific project.
    """
    context = {
        "project_name": project_info.get("name", "Django Project"),
        "python_version": project_info.get("python_version", "3.12"),
        "django_version": project_info.get("django_version", "5.2"),
        "settings_module": project_info.get("settings_module", ""),
        "models_section": format_models_section(models),
        "endpoints_section": format_endpoints_section(endpoints),
        "schemas_section": format_schemas_section(schemas),
        "auth_section": format_auth_section(endpoints),
        "async_safety_section": format_async_safety_rules(async_warnings),
        "service_layer_section": format_service_layer_section(services),
        "environment_section": format_environment_section(environment),
        "test_patterns_section": format_test_patterns_section(test_patterns),
    }
    return render_template(LLM_SYSTEM_PROMPT_TEMPLATE, context)


__all__ = [
    "CLAUDE_MD_TEMPLATE",
    "COPILOT_INSTRUCTIONS_TEMPLATE",
    "CURSOR_RULES_TEMPLATE",
    "LLM_SYSTEM_PROMPT_TEMPLATE",
    "format_async_safety_rules",
    "format_async_safety_section",
    "format_auth_section",
    "format_code_examples_section",
    "format_endpoints_rules",
    "format_endpoints_section",
    "format_environment_section",
    "format_error_handling_section",
    "format_llm_prompt",
    "format_models_rules",
    "format_models_section",
    "format_schema_rules",
    "format_schemas_section",
    "format_service_layer_section",
    "format_tech_stack",
    "format_test_patterns_section",
    "get_template",
    "render_template",
]
