# Generated by Django 6.0.5 on 2026-05-19 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("company_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("tech_used", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "experience",
                "ordering": ["order", "-start_date"],
            },
        ),
    ]
