# file-length-max: 500
"""
Configuration system for code generation.

Supports loading configuration from:
1. `django_matt_codegen.py` in project root
2. Django settings (`DJANGO_MATT_CODEGEN` dict)
3. `pyproject.toml` under `[tool.django-matt.codegen]`
4. Programmatic configuration via `CodegenConfig`

Usage:
    from django_matt.codegen.config import load_config, CodegenConfig

    # Load from file/settings (auto-discovers)
    config = load_config()

    # Or create programmatically
    config = CodegenConfig(
        framework="react",
        ui_library="shadcn",
        output_dir="./frontend/src/generated",
        models=["users.User", "posts.Post"],
    )

    # Use with generators
    from django_matt.codegen import ReactGenerator
    generator = ReactGenerator.from_config(config)
"""

from __future__ import annotations

import importlib.util
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

# Supported frameworks and UI libraries
Framework = Literal["react", "svelte", "solid", "typescript"]
UILibrary = Literal["shadcn", "tailwind", "headless", "none"]


@dataclass
class ModelConfig:
    """Configuration for a specific model."""

    # Full path to the model (e.g., "users.User")
    path: str

    # Optional output directory override for this model
    output_dir: str | None = None

    # Fields to exclude from generation
    exclude_fields: list[str] = field(default_factory=list)

    # Fields to include (if specified, only these are included)
    include_fields: list[str] = field(default_factory=list)

    # Whether to generate CRUD components
    generate_crud: bool = True

    # Whether to generate form components
    generate_forms: bool = True

    # Whether to generate list/table components
    generate_lists: bool = True

    # Whether to generate hooks/queries
    generate_hooks: bool = True

    # Custom display name for the model
    display_name: str | None = None

    @classmethod
    def from_string(cls, path: str) -> ModelConfig:
        """Create a ModelConfig from a simple string path."""
        return cls(path=path)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ModelConfig:
        """Create a ModelConfig from a dictionary."""
        return cls(
            path=data["path"],
            output_dir=data.get("output_dir"),
            exclude_fields=data.get("exclude_fields", []),
            include_fields=data.get("include_fields", []),
            generate_crud=data.get("generate_crud", True),
            generate_forms=data.get("generate_forms", True),
            generate_lists=data.get("generate_lists", True),
            generate_hooks=data.get("generate_hooks", True),
            display_name=data.get("display_name"),
        )


@dataclass
class CodegenConfig:
    """Configuration for code generation."""

    # Target framework
    framework: Framework = "react"

    # UI library to use
    ui_library: UILibrary = "shadcn"

    # Output directory for generated files
    output_dir: str = "./frontend/src/generated"

    # Models to generate code for
    models: list[str | ModelConfig] = field(default_factory=list)

    # TypeScript settings
    use_typescript: bool = True
    camel_case: bool = True

    # Zod schema generation
    generate_zod: bool = True

    # API client settings
    base_url: str = "/api"
    include_api_client: bool = True

    # Watch mode settings (can be overridden by CLI)
    watch_dirs: list[str] = field(default_factory=list)
    debounce_delay: float = 0.5
    poll_interval: float = 1.0

    # Component generation settings
    component_prefix: str = ""
    component_suffix: str = ""

    # Import paths for UI components (e.g., "@/components/ui")
    ui_import_path: str = "@/components/ui"

    # Hooks import path (e.g., "@/generated/hooks")
    hooks_import_path: str = "@/generated/hooks"

    # Types import path (e.g., "@/generated/types")
    types_import_path: str = "@/generated/types"

    # Whether to generate index files
    generate_index: bool = True

    # Custom code to inject at the top of generated files
    header: str = "// Auto-generated by django-matt codegen\n// Do not edit manually\n"

    def get_model_configs(self) -> list[ModelConfig]:
        """Get all models as ModelConfig objects."""
        configs = []
        for model in self.models:
            if isinstance(model, str):
                configs.append(ModelConfig.from_string(model))
            elif isinstance(model, dict):
                configs.append(ModelConfig.from_dict(model))
            elif isinstance(model, ModelConfig):
                configs.append(model)
        return configs

    def get_output_path(self) -> Path:
        """Get the output directory as a Path object."""
        return Path(self.output_dir)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CodegenConfig:
        """Create a CodegenConfig from a dictionary."""
        # Handle models specially - they can be strings or dicts
        models = []
        for model in data.get("models", []):
            if isinstance(model, str):
                models.append(model)
            elif isinstance(model, dict):
                models.append(ModelConfig.from_dict(model))

        return cls(
            framework=data.get("framework", "react"),
            ui_library=data.get("ui_library", "shadcn"),
            output_dir=data.get("output_dir", "./frontend/src/generated"),
            models=models,
            use_typescript=data.get("use_typescript", True),
            camel_case=data.get("camel_case", True),
            generate_zod=data.get("generate_zod", True),
            base_url=data.get("base_url", "/api"),
            include_api_client=data.get("include_api_client", True),
            watch_dirs=data.get("watch_dirs", []),
            debounce_delay=data.get("debounce_delay", 0.5),
            poll_interval=data.get("poll_interval", 1.0),
            component_prefix=data.get("component_prefix", ""),
            component_suffix=data.get("component_suffix", ""),
            ui_import_path=data.get("ui_import_path", "@/components/ui"),
            hooks_import_path=data.get("hooks_import_path", "@/generated/hooks"),
            types_import_path=data.get("types_import_path", "@/generated/types"),
            generate_index=data.get("generate_index", True),
            header=data.get(
                "header", "// Auto-generated by django-matt codegen\n// Do not edit manually\n"
            ),
        )


def _load_from_python_file(file_path: Path) -> dict[str, Any] | None:
    """Load configuration from a Python file."""
    if not file_path.exists():
        return None

    spec = importlib.util.spec_from_file_location("django_matt_codegen", file_path)
    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    sys.modules["django_matt_codegen"] = module
    spec.loader.exec_module(module)

    # Look for CODEGEN dict
    if hasattr(module, "CODEGEN"):
        return module.CODEGEN

    return None


def _load_from_django_settings() -> dict[str, Any] | None:
    """Load configuration from Django settings."""
    try:
        from django.conf import settings

        if hasattr(settings, "DJANGO_MATT_CODEGEN"):
            return settings.DJANGO_MATT_CODEGEN
    except Exception:
        pass

    return None


def _load_from_pyproject_toml(project_root: Path) -> dict[str, Any] | None:
    """Load configuration from pyproject.toml."""
    pyproject_path = project_root / "pyproject.toml"
    if not pyproject_path.exists():
        return None

    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore[import-not-found,no-redef]
        except ImportError:
            return None

    try:
        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)

        # Look for [tool.django-matt.codegen]
        return data.get("tool", {}).get("django-matt", {}).get("codegen")
    except Exception:
        return None


def find_project_root() -> Path:
    """Find the project root directory."""
    # Start from current working directory
    cwd = Path.cwd()

    # Look for common project markers
    markers = ["manage.py", "pyproject.toml", "setup.py", ".git"]

    current = cwd
    while current != current.parent:
        for marker in markers:
            if (current / marker).exists():
                return current
        current = current.parent

    # Fall back to cwd
    return cwd


def load_config(
    config_file: str | Path | None = None,
    project_root: Path | None = None,
) -> CodegenConfig:
    """
    Load codegen configuration from available sources.

    Search order:
    1. Explicit config_file if provided
    2. django_matt_codegen.py in project root
    3. Django settings DJANGO_MATT_CODEGEN
    4. pyproject.toml [tool.django-matt.codegen]
    5. Default configuration

    Args:
        config_file: Explicit path to config file
        project_root: Project root directory (auto-detected if not provided)

    Returns:
        CodegenConfig with loaded configuration
    """
    if project_root is None:
        project_root = find_project_root()

    config_data: dict[str, Any] | None = None

    # 1. Try explicit config file
    if config_file is not None:
        config_path = Path(config_file)
        if config_path.suffix == ".py":
            config_data = _load_from_python_file(config_path)
        elif config_path.suffix == ".toml":
            config_data = _load_from_pyproject_toml(config_path.parent)

    # 2. Try django_matt_codegen.py
    if config_data is None:
        config_data = _load_from_python_file(project_root / "django_matt_codegen.py")

    # 3. Try Django settings
    if config_data is None:
        config_data = _load_from_django_settings()

    # 4. Try pyproject.toml
    if config_data is None:
        config_data = _load_from_pyproject_toml(project_root)

    # 5. Return default config
    if config_data is None:
        return CodegenConfig()

    return CodegenConfig.from_dict(config_data)


def create_config_file(
    output_path: Path | None = None,
    framework: Framework = "react",
    ui_library: UILibrary = "shadcn",
    output_dir: str = "./frontend/src/generated",
    models: list[str] | None = None,
) -> str:
    """
    Generate a django_matt_codegen.py config file.

    Args:
        output_path: Where to write the file (if None, just returns content)
        framework: Target framework
        ui_library: UI library to use
        output_dir: Output directory
        models: List of model paths

    Returns:
        The generated config file content
    """
    models_list = models or []
    models_str = ",\n        ".join(f'"{m}"' for m in models_list)

    content = f'''"""
Django Matt Codegen Configuration.

This file configures the code generation settings for your frontend.
Run `python manage.py sync_types` to generate code based on this config.
"""

CODEGEN = {{
    # Target framework: "react", "svelte", "solid", or "typescript"
    "framework": "{framework}",

    # UI library: "shadcn", "tailwind", "headless", or "none"
    "ui_library": "{ui_library}",

    # Output directory for generated files
    "output_dir": "{output_dir}",

    # Models to generate code for
    # Can be simple strings or dicts with more options
    "models": [
        {models_str}
    ],

    # TypeScript settings
    "use_typescript": True,
    "camel_case": True,

    # Generate Zod schemas for runtime validation
    "generate_zod": True,

    # API client settings
    "base_url": "/api",
    "include_api_client": True,

    # Watch mode settings
    # "watch_dirs": [],  # Auto-detected from models
    # "debounce_delay": 0.5,
    # "poll_interval": 1.0,

    # Component generation settings
    # "component_prefix": "",
    # "component_suffix": "",

    # Import paths (adjust based on your project structure)
    "ui_import_path": "@/components/ui",
    "hooks_import_path": "@/generated/hooks",
    "types_import_path": "@/generated/types",

    # Generate index.ts files for easy imports
    "generate_index": True,
}}

# Advanced: Per-model configuration
# CODEGEN["models"] = [
#     "users.User",  # Simple string
#     {{
#         "path": "posts.Post",
#         "exclude_fields": ["internal_notes"],
#         "generate_crud": True,
#         "generate_forms": True,
#         "generate_lists": True,
#         "generate_hooks": True,
#         "display_name": "Blog Post",
#     }},
# ]
'''

    if output_path is not None:
        output_path.write_text(content)

    return content


__all__ = [
    "CodegenConfig",
    "ModelConfig",
    "Framework",
    "UILibrary",
    "load_config",
    "create_config_file",
    "find_project_root",
]
