"""Python SDK generator — produces a complete PyPI-publishable package."""

from __future__ import annotations

from typing import Any

from django_matt.sdkgen.base import SDKConfig, SDKGenerator, SDKOutput
from django_matt.sdkgen.schema_parser import Endpoint, ParsedAPI, SchemaParser
from django_matt.sdkgen.template_engine import (
    openapi_type_to_python,
    sanitize_identifier,
    to_pascal_case,
    to_snake_case,
)


class PythonSDKGenerator(SDKGenerator):
    """Generate a complete Python SDK package from an OpenAPI schema."""

    target = "python"

    def generate(self, api_schema: dict[str, Any], config: SDKConfig) -> SDKOutput:
        parser = SchemaParser(api_schema)
        api = parser.parse()

        pkg = to_snake_case(config.package_name).replace("-", "_")
        files: dict[str, str] = {}

        if config.include_models:
            files[f"{pkg}/models.py"] = self._generate_models(api)

        files[f"{pkg}/errors.py"] = self._generate_errors()
        files[f"{pkg}/auth.py"] = self._generate_auth()

        if config.include_client:
            files[f"{pkg}/client.py"] = self._generate_client(api, config, pkg)

        files[f"{pkg}/__init__.py"] = self._generate_init(pkg, config)

        pyproject = self._generate_pyproject(config, api, pkg)
        files["pyproject.toml"] = pyproject
        files["README.md"] = self._generate_readme(api, config, pkg)

        return SDKOutput(files=files, package_config=pyproject, target=self.target)

    def _generate_models(self, api: ParsedAPI) -> str:
        lines: list[str] = [
            '"""Auto-generated by django_matt.sdkgen — do not edit manually."""',
            "",
            "from __future__ import annotations",
            "",
            "from datetime import date, datetime",
            "from enum import Enum",
            "from typing import Any",
            "",
            "from pydantic import BaseModel, Field",
            "",
            "",
        ]

        for name, model in api.models.items():
            py_name = to_pascal_case(sanitize_identifier(name))

            # Enum model
            if model.enum_values is not None:
                if all(isinstance(v, str) for v in model.enum_values):
                    lines.append(f"class {py_name}(str, Enum):")
                    for v in model.enum_values:
                        attr = sanitize_identifier(to_snake_case(str(v))).upper()
                        lines.append(f'    {attr} = "{v}"')
                else:
                    lines.append(f"class {py_name}(Enum):")
                    for v in model.enum_values:
                        attr = sanitize_identifier(str(v)).upper()
                        lines.append(f"    V_{attr} = {v!r}")
                lines.append("")
                lines.append("")
                continue

            # BaseModel
            bases = ["BaseModel"]
            if model.all_of:
                for sub in model.all_of:
                    if "$ref" in sub:
                        ref_name = sub["$ref"].rsplit("/", 1)[-1]
                        bases = [to_pascal_case(sanitize_identifier(ref_name))]

            if model.description:
                lines.append(f"class {py_name}({', '.join(bases)}):")
                lines.append(f'    """{model.description}"""')
            else:
                lines.append(f"class {py_name}({', '.join(bases)}):")

            props = dict(model.properties)
            if model.all_of:
                for sub in model.all_of:
                    if "$ref" not in sub:
                        props.update(sub.get("properties", {}))

            if not props:
                lines.append("    pass")
            else:
                for prop_name, prop_schema in props.items():
                    py_type = openapi_type_to_python(prop_schema)
                    field_name = to_snake_case(prop_name)
                    is_required = prop_name in model.required_fields
                    desc = prop_schema.get("description", "")

                    if is_required:
                        if desc:
                            lines.append(f'    {field_name}: {py_type} = Field(description="{desc}")')
                        else:
                            lines.append(f"    {field_name}: {py_type}")
                    elif desc:
                        lines.append(f'    {field_name}: {py_type} | None = Field(default=None, description="{desc}")')
                    else:
                        lines.append(f"    {field_name}: {py_type} | None = None")

            lines.append("")
            lines.append("")

        return "\n".join(lines)

    def _generate_errors(self) -> str:
        return '''\
"""Auto-generated by django_matt.sdkgen — do not edit manually."""

from __future__ import annotations

from typing import Any


class APIError(Exception):
    """Base API error."""

    def __init__(self, message: str, status: int, body: Any = None) -> None:
        super().__init__(message)
        self.status = status
        self.body = body


class ValidationError(APIError):
    """422 Validation Error."""

    def __init__(self, errors: list[dict[str, str]], body: Any = None) -> None:
        super().__init__("Validation failed", 422, body)
        self.errors = errors


class AuthenticationError(APIError):
    """401 Authentication Error."""

    def __init__(self, message: str = "Authentication required", body: Any = None) -> None:
        super().__init__(message, 401, body)


class NotFoundError(APIError):
    """404 Not Found."""

    def __init__(self, message: str = "Not found", body: Any = None) -> None:
        super().__init__(message, 404, body)


class RateLimitError(APIError):
    """429 Rate Limited."""

    def __init__(
        self,
        message: str = "Rate limited",
        retry_after: float | None = None,
        body: Any = None,
    ) -> None:
        super().__init__(message, 429, body)
        self.retry_after = retry_after
'''

    def _generate_auth(self) -> str:
        return '''\
"""Auto-generated by django_matt.sdkgen — do not edit manually."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

try:
    import httpx
    _HAS_HTTPX = True
except ImportError:
    httpx = None  # type: ignore[assignment]
    _HAS_HTTPX = False


class AuthProvider(ABC):
    """Abstract auth provider."""

    @abstractmethod
    def get_headers(self) -> dict[str, str]: ...

    def on_unauthorized(self) -> None:
        """Called on 401 — override to implement token refresh."""


class JWTAuth(AuthProvider):
    """JWT bearer token auth with optional refresh."""

    def __init__(
        self,
        access_token: str,
        refresh_token: str | None = None,
        refresh_url: str | None = None,
    ) -> None:
        self.access_token = access_token
        self.refresh_token = refresh_token
        self.refresh_url = refresh_url

    def get_headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self.access_token}"}

    def on_unauthorized(self) -> None:
        if not self.refresh_token or not self.refresh_url:
            return
        if not _HAS_HTTPX:
            return
        resp = httpx.post(
            self.refresh_url,
            json={"refresh": self.refresh_token},
        )
        if resp.status_code == 200:
            data = resp.json()
            self.access_token = data["access"]
            if "refresh" in data:
                self.refresh_token = data["refresh"]


class APIKeyAuth(AuthProvider):
    """API key header auth."""

    def __init__(self, api_key: str, header_name: str = "X-API-Key") -> None:
        self.api_key = api_key
        self.header_name = header_name

    def get_headers(self) -> dict[str, str]:
        return {self.header_name: self.api_key}
'''

    def _generate_client(self, api: ParsedAPI, config: SDKConfig, pkg: str) -> str:
        lines: list[str] = [
            '"""Auto-generated by django_matt.sdkgen — do not edit manually."""',
            "",
            "from __future__ import annotations",
            "",
            "import asyncio",
            "import logging",
            "from typing import Any, AsyncIterator, Iterator",
            "",
            "try:",
            "    import httpx",
            "    _HAS_HTTPX = True",
            "except ImportError:",
            "    httpx = None  # type: ignore[assignment]",
            "    _HAS_HTTPX = False",
            "",
            f"from {pkg}.auth import AuthProvider",
            f"from {pkg}.errors import (",
            "    APIError,",
            "    AuthenticationError,",
            "    NotFoundError,",
            "    RateLimitError,",
            "    ValidationError,",
            ")",
            "",
        ]

        # Import models
        model_refs = self._collect_model_refs(api)
        if model_refs:
            imports = ", ".join(sorted(model_refs))
            lines.append(f"from {pkg}.models import {imports}")
            lines.append("")

        lines.extend([
            f'logger = logging.getLogger("{pkg}")',
            "",
            "",
            "_ERROR_MAP: dict[int, type[APIError]] = {",
            "    401: AuthenticationError,",
            "    404: NotFoundError,",
            "    429: RateLimitError,",
            "}",
            "",
            "",
        ])

        # Sync client
        lines.extend([
            "class Client:",
            '    """Synchronous API client (httpx-based)."""',
            "",
            "    def __init__(",
            "        self,",
            "        base_url: str,",
            "        auth: AuthProvider | None = None,",
            "        timeout: float = 30.0,",
            "        max_retries: int = 3,",
            "        retry_backoff: float = 0.5,",
            "    ) -> None:",
            "        if not _HAS_HTTPX:",
            '            raise ImportError("httpx is required: uv add httpx")',
            '        self._base_url = base_url.rstrip("/")',
            "        self._auth = auth",
            "        self._timeout = timeout",
            "        self._max_retries = max_retries",
            "        self._retry_backoff = retry_backoff",
            "        self._client = httpx.Client(base_url=self._base_url, timeout=timeout)",
            "",
            "    def _headers(self) -> dict[str, str]:",
            '        headers: dict[str, str] = {"Content-Type": "application/json", "Accept": "application/json"}',
            "        if self._auth:",
            "            headers.update(self._auth.get_headers())",
            "        return headers",
            "",
            "    def _request(",
            "        self,",
            "        method: str,",
            "        path: str,",
            "        *,",
            "        json: Any = None,",
            "        params: dict[str, Any] | None = None,",
            "    ) -> Any:",
            "        import time",
            "",
            "        last_error: Exception | None = None",
            "        for attempt in range(self._max_retries):",
            "            try:",
            "                resp = self._client.request(",
            "                    method, path, json=json, params=params, headers=self._headers()",
            "                )",
            "                if resp.status_code == 401 and attempt == 0 and self._auth:",
            "                    self._auth.on_unauthorized()",
            "                    continue",
            "                if resp.status_code >= 400:",
            "                    body = resp.json() if resp.content else None",
            "                    error_cls = _ERROR_MAP.get(resp.status_code, APIError)",
            "                    if resp.status_code == 422:",
            "                        errors = body.get('errors', []) if isinstance(body, dict) else []",
            "                        raise ValidationError(errors, body)",
            "                    raise error_cls(str(body), resp.status_code, body) if error_cls is APIError else error_cls(body=body)",
            "                if resp.status_code == 204:",
            "                    return None",
            "                return resp.json()",
            "            except APIError:",
            "                raise",
            "            except Exception as e:",
            "                last_error = e",
            "                if attempt < self._max_retries - 1:",
            "                    time.sleep(self._retry_backoff * (2 ** attempt))",
            '        raise last_error or APIError("Request failed", 0)',
            "",
            "    def upload_file(",
            "        self,",
            "        path: str,",
            "        file: bytes,",
            '        filename: str = "upload",',
            '        field_name: str = "file",',
            "        extra_fields: dict[str, str] | None = None,",
            "    ) -> Any:",
            "        files = {field_name: (filename, file)}",
            "        data = extra_fields or {}",
            "        headers = {}",
            "        if self._auth:",
            "            headers.update(self._auth.get_headers())",
            "        resp = self._client.post(path, files=files, data=data, headers=headers)",
            "        if resp.status_code >= 400:",
            "            body = resp.json() if resp.content else None",
            '            raise APIError(f"Upload failed: {resp.status_code}", resp.status_code, body)',
            "        return resp.json()",
            "",
            "    def close(self) -> None:",
            "        self._client.close()",
            "",
            "    def __enter__(self) -> Client:",
            "        return self",
            "",
            "    def __exit__(self, *args: Any) -> None:",
            "        self.close()",
            "",
        ])

        # Sync endpoint methods
        for ep in api.endpoints:
            self._generate_sync_method(lines, ep, "    ")

        lines.append("")
        lines.append("")

        # Async client
        lines.extend([
            "class AsyncClient:",
            '    """Asynchronous API client (httpx-based)."""',
            "",
            "    def __init__(",
            "        self,",
            "        base_url: str,",
            "        auth: AuthProvider | None = None,",
            "        timeout: float = 30.0,",
            "        max_retries: int = 3,",
            "        retry_backoff: float = 0.5,",
            "    ) -> None:",
            "        if not _HAS_HTTPX:",
            '            raise ImportError("httpx is required: uv add httpx")',
            '        self._base_url = base_url.rstrip("/")',
            "        self._auth = auth",
            "        self._timeout = timeout",
            "        self._max_retries = max_retries",
            "        self._retry_backoff = retry_backoff",
            "        self._client = httpx.AsyncClient(base_url=self._base_url, timeout=timeout)",
            "",
            "    def _headers(self) -> dict[str, str]:",
            '        headers: dict[str, str] = {"Content-Type": "application/json", "Accept": "application/json"}',
            "        if self._auth:",
            "            headers.update(self._auth.get_headers())",
            "        return headers",
            "",
            "    async def _request(",
            "        self,",
            "        method: str,",
            "        path: str,",
            "        *,",
            "        json: Any = None,",
            "        params: dict[str, Any] | None = None,",
            "    ) -> Any:",
            "        last_error: Exception | None = None",
            "        for attempt in range(self._max_retries):",
            "            try:",
            "                resp = await self._client.request(",
            "                    method, path, json=json, params=params, headers=self._headers()",
            "                )",
            "                if resp.status_code == 401 and attempt == 0 and self._auth:",
            "                    self._auth.on_unauthorized()",
            "                    continue",
            "                if resp.status_code >= 400:",
            "                    body = resp.json() if resp.content else None",
            "                    error_cls = _ERROR_MAP.get(resp.status_code, APIError)",
            "                    if resp.status_code == 422:",
            "                        errors = body.get('errors', []) if isinstance(body, dict) else []",
            "                        raise ValidationError(errors, body)",
            "                    raise error_cls(str(body), resp.status_code, body) if error_cls is APIError else error_cls(body=body)",
            "                if resp.status_code == 204:",
            "                    return None",
            "                return resp.json()",
            "            except APIError:",
            "                raise",
            "            except Exception as e:",
            "                last_error = e",
            "                if attempt < self._max_retries - 1:",
            "                    await asyncio.sleep(self._retry_backoff * (2 ** attempt))",
            '        raise last_error or APIError("Request failed", 0)',
            "",
            "    async def upload_file(",
            "        self,",
            "        path: str,",
            "        file: bytes,",
            '        filename: str = "upload",',
            '        field_name: str = "file",',
            "        extra_fields: dict[str, str] | None = None,",
            "    ) -> Any:",
            "        files = {field_name: (filename, file)}",
            "        data = extra_fields or {}",
            "        headers = {}",
            "        if self._auth:",
            "            headers.update(self._auth.get_headers())",
            "        resp = await self._client.post(path, files=files, data=data, headers=headers)",
            "        if resp.status_code >= 400:",
            "            body = resp.json() if resp.content else None",
            '            raise APIError(f"Upload failed: {resp.status_code}", resp.status_code, body)',
            "        return resp.json()",
            "",
            "    async def close(self) -> None:",
            "        await self._client.aclose()",
            "",
            "    async def __aenter__(self) -> AsyncClient:",
            "        return self",
            "",
            "    async def __aexit__(self, *args: Any) -> None:",
            "        await self.close()",
            "",
        ])

        # Async endpoint methods
        for ep in api.endpoints:
            self._generate_async_method(lines, ep, "    ")

        lines.append("")

        return "\n".join(lines)

    def _generate_sync_method(self, lines: list[str], ep: Endpoint, prefix: str) -> None:
        method_name = to_snake_case(sanitize_identifier(ep.operation_id))
        params, path_expr, body_arg, query_arg = self._method_parts(ep)

        sig = ", ".join(["self"] + params)
        return_type = self._return_type(ep)

        if ep.summary:
            lines.append(f'{prefix}def {method_name}({sig}) -> {return_type}:')
            lines.append(f'{prefix}    """{ep.summary}"""')
        else:
            lines.append(f"{prefix}def {method_name}({sig}) -> {return_type}:")

        lines.append(f'{prefix}    return self._request("{ep.method}", {path_expr}{body_arg}{query_arg})')
        lines.append("")

    def _generate_async_method(self, lines: list[str], ep: Endpoint, prefix: str) -> None:
        method_name = to_snake_case(sanitize_identifier(ep.operation_id))
        params, path_expr, body_arg, query_arg = self._method_parts(ep)

        sig = ", ".join(["self"] + params)
        return_type = self._return_type(ep)

        if ep.summary:
            lines.append(f'{prefix}async def {method_name}({sig}) -> {return_type}:')
            lines.append(f'{prefix}    """{ep.summary}"""')
        else:
            lines.append(f"{prefix}async def {method_name}({sig}) -> {return_type}:")

        lines.append(f'{prefix}    return await self._request("{ep.method}", {path_expr}{body_arg}{query_arg})')
        lines.append("")

    def _method_parts(self, ep: Endpoint) -> tuple[list[str], str, str, str]:
        """Build method parameters, path expression, body arg, query arg."""
        params: list[str] = []

        # Path params
        for p in ep.parameters:
            if p.location == "path":
                py_type = openapi_type_to_python(p.schema) if p.schema else "str"
                params.append(f"{to_snake_case(p.name)}: {py_type}")

        # Body
        body_arg = ""
        if ep.request_body_ref:
            body_type = to_pascal_case(sanitize_identifier(ep.request_body_ref))
            params.append(f"data: {body_type}")
            body_arg = ", json=data.model_dump(mode='json')"
        elif ep.request_body_schema and ep.request_body_schema.get("type") == "object":
            params.append("data: dict[str, Any]")
            body_arg = ", json=data"

        # Query params
        query_params = [p for p in ep.parameters if p.location == "query"]
        query_arg = ""
        if query_params:
            for qp in query_params:
                py_type = openapi_type_to_python(qp.schema) if qp.schema else "str"
                default = " = None" if not qp.required else ""
                if not qp.required:
                    py_type = f"{py_type} | None"
                params.append(f"{to_snake_case(qp.name)}: {py_type}{default}")
            param_names = [to_snake_case(qp.name) for qp in query_params]
            dict_items = ", ".join(f'"{qp.name}": {to_snake_case(qp.name)}' for qp in query_params)
            query_arg = f", params={{{dict_items}}}"

        # Path expression
        path = ep.path
        path_params = [p for p in ep.parameters if p.location == "path"]
        if path_params:
            for p in path_params:
                path = path.replace(f"{{{p.name}}}", f"{{{to_snake_case(p.name)}}}")
            path_expr = f'f"{path}"'
        else:
            path_expr = f'"{path}"'

        return params, path_expr, body_arg, query_arg

    def _return_type(self, ep: Endpoint) -> str:
        if ep.response_ref:
            return to_pascal_case(sanitize_identifier(ep.response_ref))
        return "Any"

    def _collect_model_refs(self, api: ParsedAPI) -> set[str]:
        refs: set[str] = set()
        for ep in api.endpoints:
            if ep.request_body_ref:
                refs.add(to_pascal_case(sanitize_identifier(ep.request_body_ref)))
            if ep.response_ref:
                refs.add(to_pascal_case(sanitize_identifier(ep.response_ref)))
        return refs

    def _generate_init(self, pkg: str, config: SDKConfig) -> str:
        return f'''\
"""Auto-generated by django_matt.sdkgen — do not edit manually."""

from {pkg}.auth import APIKeyAuth, AuthProvider, JWTAuth
from {pkg}.client import AsyncClient, Client
from {pkg}.errors import (
    APIError,
    AuthenticationError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)

__all__ = [
    "APIKeyAuth",
    "AsyncClient",
    "AuthProvider",
    "AuthenticationError",
    "APIError",
    "Client",
    "JWTAuth",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
]
'''

    def _generate_pyproject(self, config: SDKConfig, api: ParsedAPI, pkg: str) -> str:
        name = config.package_name.replace("_", "-")
        return f"""\
[project]
name = "{name}"
version = "{config.version}"
description = "{config.description or f'Python client for {api.title}'}"
requires-python = ">=3.12"
license = "{config.license}"
dependencies = [
    "httpx>=0.27",
    "pydantic>=2.0",
]

[project.optional-dependencies]
websockets = ["websockets>=12.0"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
"""

    def _generate_readme(self, api: ParsedAPI, config: SDKConfig, pkg: str) -> str:
        name = config.package_name.replace("_", "-")
        return f"""\
# {name}

Python client for {api.title} v{api.version}.

Auto-generated by django_matt.sdkgen.

## Installation

```bash
uv add {name}
```

## Usage

### Sync

```python
from {pkg} import Client, JWTAuth

client = Client(
    base_url="{config.base_url}",
    auth=JWTAuth(access_token="your-token"),
)
```

### Async

```python
from {pkg} import AsyncClient, JWTAuth

async with AsyncClient(
    base_url="{config.base_url}",
    auth=JWTAuth(access_token="your-token"),
) as client:
    pass
```
"""
