"""Swift SDK generator — produces a Swift Package Manager package."""

from __future__ import annotations

from typing import Any

from django_matt.sdkgen.base import SDKConfig, SDKGenerator, SDKOutput
from django_matt.sdkgen.schema_parser import Endpoint, ParsedAPI, SchemaParser
from django_matt.sdkgen.template_engine import (
    openapi_type_to_swift,
    sanitize_identifier,
    to_camel_case,
    to_pascal_case,
)


class SwiftSDKGenerator(SDKGenerator):
    """Generate a complete Swift package from an OpenAPI schema."""

    target = "swift"

    def generate(self, api_schema: dict[str, Any], config: SDKConfig) -> SDKOutput:
        parser = SchemaParser(api_schema)
        api = parser.parse()

        pkg_name = to_pascal_case(config.package_name)
        files: dict[str, str] = {}

        if config.include_models:
            files[f"Sources/{pkg_name}/Models.swift"] = self._generate_models(api)

        files[f"Sources/{pkg_name}/Auth.swift"] = self._generate_auth()
        files[f"Sources/{pkg_name}/Errors.swift"] = self._generate_errors()

        if config.include_client:
            files[f"Sources/{pkg_name}/Client.swift"] = self._generate_client(api, config)

        package_swift = self._generate_package_swift(config, pkg_name)
        files["Package.swift"] = package_swift
        files["README.md"] = self._generate_readme(api, config, pkg_name)

        return SDKOutput(files=files, package_config=package_swift, target=self.target)

    def _generate_models(self, api: ParsedAPI) -> str:
        lines: list[str] = [
            "// Auto-generated by django_matt.sdkgen",
            "// Do not edit manually",
            "",
            "import Foundation",
            "",
        ]

        for name, model in api.models.items():
            swift_name = to_pascal_case(sanitize_identifier(name))

            # Enum
            if model.enum_values is not None:
                if all(isinstance(v, str) for v in model.enum_values):
                    lines.append(f"public enum {swift_name}: String, Codable, CaseIterable {{")
                    for v in model.enum_values:
                        case_name = to_camel_case(sanitize_identifier(str(v)))
                        lines.append(f'    case {case_name} = "{v}"')
                    lines.append("}")
                else:
                    lines.append(f"public enum {swift_name}: Codable {{")
                    for v in model.enum_values:
                        lines.append(f"    case value{v}")
                    lines.append("}")
                lines.append("")
                continue

            # Struct
            if model.description:
                lines.append(f"/// {model.description}")
            lines.append(f"public struct {swift_name}: Codable, Sendable {{")

            props = dict(model.properties)
            if model.all_of:
                for sub in model.all_of:
                    if "$ref" not in sub:
                        props.update(sub.get("properties", {}))

            for prop_name, prop_schema in props.items():
                swift_type = openapi_type_to_swift(prop_schema)
                field_name = to_camel_case(sanitize_identifier(prop_name))
                is_required = prop_name in model.required_fields
                if not is_required and "?" not in swift_type:
                    swift_type = f"{swift_type}?"
                desc = prop_schema.get("description", "")
                if desc:
                    lines.append(f"    /// {desc}")
                lines.append(f"    public let {field_name}: {swift_type}")

            # CodingKeys if snake_case -> camelCase mapping needed
            coding_keys = []
            for prop_name in props:
                camel = to_camel_case(sanitize_identifier(prop_name))
                if camel != prop_name:
                    coding_keys.append((camel, prop_name))

            if coding_keys:
                lines.append("")
                lines.append("    enum CodingKeys: String, CodingKey {")
                for camel, original in coding_keys:
                    lines.append(f'        case {camel} = "{original}"')
                # Also emit keys that didn't need remapping
                for prop_name in props:
                    camel = to_camel_case(sanitize_identifier(prop_name))
                    if camel == prop_name:
                        lines.append(f"        case {camel}")
                lines.append("    }")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def _generate_errors(self) -> str:
        return """\
// Auto-generated by django_matt.sdkgen

import Foundation

public enum APIError: Error, LocalizedError {
    case httpError(status: Int, body: Data?)
    case authenticationError
    case notFound
    case validationError(errors: [ValidationFieldError])
    case rateLimited(retryAfter: TimeInterval?)
    case networkError(Error)
    case decodingError(Error)

    public var errorDescription: String? {
        switch self {
        case .httpError(let status, _):
            return "HTTP error: \\(status)"
        case .authenticationError:
            return "Authentication required"
        case .notFound:
            return "Resource not found"
        case .validationError(let errors):
            return "Validation failed: \\(errors.map(\\.message).joined(separator: ", "))"
        case .rateLimited(let retryAfter):
            if let seconds = retryAfter {
                return "Rate limited. Retry after \\(seconds)s"
            }
            return "Rate limited"
        case .networkError(let error):
            return "Network error: \\(error.localizedDescription)"
        case .decodingError(let error):
            return "Decoding error: \\(error.localizedDescription)"
        }
    }
}

public struct ValidationFieldError: Codable, Sendable {
    public let field: String
    public let message: String
}
"""

    def _generate_auth(self) -> str:
        return """\
// Auto-generated by django_matt.sdkgen

import Foundation

public protocol AuthProvider: Sendable {
    func getHeaders() async -> [String: String]
    func onUnauthorized() async
}

public extension AuthProvider {
    func onUnauthorized() async {}
}

public final class JWTAuth: AuthProvider, @unchecked Sendable {
    private var accessToken: String
    private var refreshToken: String?
    private let refreshURL: URL?

    public init(accessToken: String, refreshToken: String? = nil, refreshURL: URL? = nil) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.refreshURL = refreshURL
    }

    public func getHeaders() async -> [String: String] {
        ["Authorization": "Bearer \\(accessToken)"]
    }

    public func onUnauthorized() async {
        guard let refreshToken, let refreshURL else { return }
        var request = URLRequest(url: refreshURL)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try? JSONEncoder().encode(["refresh": refreshToken])

        guard let (data, response) = try? await URLSession.shared.data(for: request),
              let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200,
              let json = try? JSONDecoder().decode([String: String].self, from: data),
              let newAccess = json["access"] else { return }

        self.accessToken = newAccess
        if let newRefresh = json["refresh"] {
            self.refreshToken = newRefresh
        }
    }

    public func setTokens(access: String, refresh: String? = nil) {
        self.accessToken = access
        if let refresh { self.refreshToken = refresh }
    }
}

public final class APIKeyAuth: AuthProvider, @unchecked Sendable {
    private let apiKey: String
    private let headerName: String

    public init(apiKey: String, headerName: String = "X-API-Key") {
        self.apiKey = apiKey
        self.headerName = headerName
    }

    public func getHeaders() async -> [String: String] {
        [headerName: apiKey]
    }
}
"""

    def _generate_client(self, api: ParsedAPI, config: SDKConfig) -> str:
        lines: list[str] = [
            "// Auto-generated by django_matt.sdkgen",
            "",
            "import Foundation",
            "",
            "public actor Client {",
            "    private let baseURL: URL",
            "    private let auth: AuthProvider?",
            "    private let session: URLSession",
            "    private let maxRetries: Int",
            "    private let retryDelay: TimeInterval",
            "    private let decoder: JSONDecoder",
            "    private let encoder: JSONEncoder",
            "",
            "    public init(",
            "        baseURL: URL,",
            "        auth: AuthProvider? = nil,",
            "        session: URLSession = .shared,",
            "        maxRetries: Int = 3,",
            "        retryDelay: TimeInterval = 0.5",
            "    ) {",
            "        self.baseURL = baseURL",
            "        self.auth = auth",
            "        self.session = session",
            "        self.maxRetries = maxRetries",
            "        self.retryDelay = retryDelay",
            "        self.decoder = JSONDecoder()",
            "        self.encoder = JSONEncoder()",
            "        self.decoder.dateDecodingStrategy = .iso8601",
            "        self.encoder.dateEncodingStrategy = .iso8601",
            "    }",
            "",
            "    private func request<T: Decodable>(",
            "        method: String,",
            "        path: String,",
            "        body: (any Encodable)? = nil,",
            "        queryItems: [URLQueryItem]? = nil",
            "    ) async throws -> T {",
            "        var components = URLComponents(url: baseURL.appendingPathComponent(path), resolvingAgainstBaseURL: true)!",
            "        components.queryItems = queryItems",
            "",
            "        guard let url = components.url else {",
            '            throw APIError.httpError(status: 0, body: nil)',
            "        }",
            "",
            "        var urlRequest = URLRequest(url: url)",
            "        urlRequest.httpMethod = method",
            '        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")',
            "",
            "        if let auth {",
            "            let headers = await auth.getHeaders()",
            "            for (key, value) in headers {",
            "                urlRequest.setValue(value, forHTTPHeaderField: key)",
            "            }",
            "        }",
            "",
            "        if let body {",
            "            urlRequest.httpBody = try encoder.encode(body)",
            "        }",
            "",
            "        var lastError: Error?",
            "",
            "        for attempt in 0...maxRetries {",
            "            if attempt > 0 {",
            "                try await Task.sleep(nanoseconds: UInt64(retryDelay * Double(1 << (attempt - 1)) * 1_000_000_000))",
            "            }",
            "",
            "            do {",
            "                let (data, response) = try await session.data(for: urlRequest)",
            "                guard let httpResponse = response as? HTTPURLResponse else {",
            '                    throw APIError.httpError(status: 0, body: nil)',
            "                }",
            "",
            "                if httpResponse.statusCode == 401 && attempt == 0 {",
            "                    await auth?.onUnauthorized()",
            "                    continue",
            "                }",
            "",
            "                guard (200..<300).contains(httpResponse.statusCode) else {",
            "                    throw self.mapError(status: httpResponse.statusCode, data: data)",
            "                }",
            "",
            "                return try decoder.decode(T.self, from: data)",
            "            } catch let error as APIError {",
            "                throw error",
            "            } catch {",
            "                lastError = error",
            "                if attempt == maxRetries { throw APIError.networkError(error) }",
            "            }",
            "        }",
            "",
            '        throw lastError ?? APIError.httpError(status: 0, body: nil)',
            "    }",
            "",
            "    private func requestVoid(",
            "        method: String,",
            "        path: String,",
            "        body: (any Encodable)? = nil,",
            "        queryItems: [URLQueryItem]? = nil",
            "    ) async throws {",
            "        let _: EmptyResponse = try await request(method: method, path: path, body: body, queryItems: queryItems)",
            "    }",
            "",
            "    private func mapError(status: Int, data: Data) -> APIError {",
            "        switch status {",
            "        case 401: return .authenticationError",
            "        case 404: return .notFound",
            "        case 422:",
            "            let errors = (try? decoder.decode([ValidationFieldError].self, from: data)) ?? []",
            "            return .validationError(errors: errors)",
            "        case 429:",
            "            return .rateLimited(retryAfter: nil)",
            "        default:",
            "            return .httpError(status: status, body: data)",
            "        }",
            "    }",
            "",
        ]

        # Endpoint methods
        for ep in api.endpoints:
            self._generate_swift_method(lines, ep)

        lines.extend([
            "}",
            "",
            "private struct EmptyResponse: Decodable {}",
            "",
        ])

        return "\n".join(lines)

    def _generate_swift_method(self, lines: list[str], ep: Endpoint) -> None:
        method_name = to_camel_case(sanitize_identifier(ep.operation_id))
        params: list[str] = []

        # Path params
        for p in ep.parameters:
            if p.location == "path":
                swift_type = openapi_type_to_swift(p.schema) if p.schema else "String"
                params.append(f"{to_camel_case(p.name)}: {swift_type}")

        # Body
        has_body = False
        if ep.request_body_ref:
            body_type = to_pascal_case(sanitize_identifier(ep.request_body_ref))
            params.append(f"data: {body_type}")
            has_body = True

        # Return type
        if ep.response_ref:
            return_type = to_pascal_case(sanitize_identifier(ep.response_ref))
            returns_value = True
        else:
            return_type = "Void"
            returns_value = False

        sig = ", ".join(params)
        if ep.summary:
            lines.append(f"    /// {ep.summary}")

        if returns_value:
            lines.append(f"    public func {method_name}({sig}) async throws -> {return_type} {{")
        else:
            lines.append(f"    public func {method_name}({sig}) async throws {{")

        # Build path
        path = ep.path
        path_params = [p for p in ep.parameters if p.location == "path"]
        if path_params:
            for p in path_params:
                path = path.replace(f"{{{p.name}}}", f"\\({to_camel_case(p.name)})")
            path_expr = f'"{path}"'
        else:
            path_expr = f'"{path}"'

        body_arg = ", body: data" if has_body else ""

        if returns_value:
            lines.append(f'        return try await request(method: "{ep.method}", path: {path_expr}{body_arg})')
        else:
            lines.append(f'        try await requestVoid(method: "{ep.method}", path: {path_expr}{body_arg})')

        lines.append("    }")
        lines.append("")

    def _generate_package_swift(self, config: SDKConfig, pkg_name: str) -> str:
        return f"""\
// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "{pkg_name}",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "{pkg_name}", targets: ["{pkg_name}"]),
    ],
    targets: [
        .target(name: "{pkg_name}"),
        .testTarget(name: "{pkg_name}Tests", dependencies: ["{pkg_name}"]),
    ]
)
"""

    def _generate_readme(self, api: ParsedAPI, config: SDKConfig, pkg_name: str) -> str:
        return f"""\
# {pkg_name}

Swift client for {api.title} v{api.version}.

Auto-generated by django_matt.sdkgen.

## Installation

Add to your `Package.swift`:

```swift
dependencies: [
    .package(url: "https://github.com/your-org/{pkg_name}", from: "{config.version}"),
]
```

## Usage

```swift
import {pkg_name}

let client = Client(
    baseURL: URL(string: "{config.base_url}")!,
    auth: JWTAuth(accessToken: "your-token")
)
```
"""
