"""TypeScript SDK generator — produces a complete npm-publishable package."""

from __future__ import annotations

import json
from typing import Any

from django_matt.sdkgen.base import SDKConfig, SDKGenerator, SDKOutput
from django_matt.sdkgen.schema_parser import Endpoint, ParsedAPI, SchemaParser
from django_matt.sdkgen.template_engine import (
    openapi_type_to_ts,
    sanitize_identifier,
    to_camel_case,
    to_kebab_case,
    to_pascal_case,
)


class TypeScriptSDKGenerator(SDKGenerator):
    """Generate a complete TypeScript SDK package from an OpenAPI schema."""

    target = "typescript"

    def generate(self, api_schema: dict[str, Any], config: SDKConfig) -> SDKOutput:
        parser = SchemaParser(api_schema)
        api = parser.parse()

        files: dict[str, str] = {}

        if config.include_models:
            files["src/models.ts"] = self._generate_models(api)

        files["src/errors.ts"] = self._generate_errors()
        files["src/auth.ts"] = self._generate_auth(config)

        if config.include_client:
            files["src/client.ts"] = self._generate_client(api, config)

        files["src/index.ts"] = self._generate_index(config)

        pkg_json = self._generate_package_json(config, api)
        files["package.json"] = pkg_json
        files["tsconfig.json"] = self._generate_tsconfig()
        files["README.md"] = self._generate_readme(api, config)

        return SDKOutput(files=files, package_config=pkg_json, target=self.target)

    def _generate_models(self, api: ParsedAPI) -> str:
        """Generate TypeScript interfaces from schema models."""
        lines: list[str] = [
            "// Auto-generated by django_matt.sdkgen",
            "// Do not edit manually",
            "",
        ]

        for name, model in api.models.items():
            ts_name = to_pascal_case(sanitize_identifier(name))

            if model.enum_values is not None:
                # Enum type
                if all(isinstance(v, str) for v in model.enum_values):
                    vals = " | ".join(f'"{v}"' for v in model.enum_values)
                else:
                    vals = " | ".join(str(v) for v in model.enum_values)
                lines.append(f"export type {ts_name} = {vals};")
                lines.append("")
                continue

            # Handle allOf (inheritance/composition)
            if model.all_of:
                extends: list[str] = []
                extra_props: dict[str, dict[str, Any]] = {}
                extra_required: list[str] = []
                for sub in model.all_of:
                    if "$ref" in sub:
                        ref_name = sub["$ref"].rsplit("/", 1)[-1]
                        extends.append(to_pascal_case(sanitize_identifier(ref_name)))
                    else:
                        extra_props.update(sub.get("properties", {}))
                        extra_required.extend(sub.get("required", []))

                ext = f" extends {', '.join(extends)}" if extends else ""
                lines.append(f"export interface {ts_name}{ext} {{")
                for prop_name, prop_schema in extra_props.items():
                    ts_type = openapi_type_to_ts(prop_schema)
                    optional = "" if prop_name in extra_required else "?"
                    lines.append(f"  {to_camel_case(prop_name)}{optional}: {ts_type};")
                lines.append("}")
                lines.append("")
                continue

            # Regular interface
            if model.description:
                lines.append(f"/** {model.description} */")
            lines.append(f"export interface {ts_name} {{")

            for prop_name, prop_schema in model.properties.items():
                ts_type = openapi_type_to_ts(prop_schema)
                optional = "" if prop_name in model.required_fields else "?"
                desc = prop_schema.get("description", "")
                if desc:
                    lines.append(f"  /** {desc} */")
                lines.append(f"  {to_camel_case(prop_name)}{optional}: {ts_type};")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def _generate_errors(self) -> str:
        return """\
// Auto-generated by django_matt.sdkgen

export class APIError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly body?: unknown,
  ) {
    super(message);
    this.name = "APIError";
  }
}

export class ValidationError extends APIError {
  constructor(
    public readonly errors: Array<{ field: string; message: string }>,
    body?: unknown,
  ) {
    super("Validation failed", 422, body);
    this.name = "ValidationError";
  }
}

export class AuthenticationError extends APIError {
  constructor(message = "Authentication required", body?: unknown) {
    super(message, 401, body);
    this.name = "AuthenticationError";
  }
}

export class NotFoundError extends APIError {
  constructor(message = "Not found", body?: unknown) {
    super(message, 404, body);
    this.name = "NotFoundError";
  }
}

export class RateLimitError extends APIError {
  public readonly retryAfter: number | null;

  constructor(message = "Rate limited", retryAfter: number | null = null, body?: unknown) {
    super(message, 429, body);
    this.name = "RateLimitError";
    this.retryAfter = retryAfter;
  }
}
"""

    def _generate_auth(self, config: SDKConfig) -> str:
        lines: list[str] = [
            "// Auto-generated by django_matt.sdkgen",
            "",
            "export interface AuthProvider {",
            "  getHeaders(): Promise<Record<string, string>>;",
            "  onUnauthorized?(): Promise<void>;",
            "}",
            "",
        ]

        # JWT auth
        lines.extend([
            "export class JWTAuth implements AuthProvider {",
            "  private accessToken: string;",
            "  private refreshToken: string | null;",
            "  private refreshUrl: string | null;",
            "",
            "  constructor(opts: {",
            "    accessToken: string;",
            "    refreshToken?: string;",
            "    refreshUrl?: string;",
            "  }) {",
            "    this.accessToken = opts.accessToken;",
            "    this.refreshToken = opts.refreshToken ?? null;",
            "    this.refreshUrl = opts.refreshUrl ?? null;",
            "  }",
            "",
            "  async getHeaders(): Promise<Record<string, string>> {",
            "    return { Authorization: `Bearer ${this.accessToken}` };",
            "  }",
            "",
            "  async onUnauthorized(): Promise<void> {",
            "    if (!this.refreshToken || !this.refreshUrl) return;",
            "    const resp = await fetch(this.refreshUrl, {",
            "      method: \"POST\",",
            '      headers: { "Content-Type": "application/json" },',
            "      body: JSON.stringify({ refresh: this.refreshToken }),",
            "    });",
            "    if (resp.ok) {",
            "      const data = await resp.json();",
            "      this.accessToken = data.access;",
            "      if (data.refresh) this.refreshToken = data.refresh;",
            "    }",
            "  }",
            "",
            "  setTokens(access: string, refresh?: string): void {",
            "    this.accessToken = access;",
            "    if (refresh) this.refreshToken = refresh;",
            "  }",
            "}",
            "",
        ])

        # API key auth
        lines.extend([
            "export class APIKeyAuth implements AuthProvider {",
            "  constructor(",
            "    private apiKey: string,",
            '    private headerName: string = "X-API-Key",',
            "  ) {}",
            "",
            "  async getHeaders(): Promise<Record<string, string>> {",
            "    return { [this.headerName]: this.apiKey };",
            "  }",
            "}",
            "",
        ])

        return "\n".join(lines)

    def _generate_client(self, api: ParsedAPI, config: SDKConfig) -> str:
        lines: list[str] = [
            "// Auto-generated by django_matt.sdkgen",
            "",
            "import type { AuthProvider } from \"./auth\";",
            "import {",
            "  APIError,",
            "  AuthenticationError,",
            "  NotFoundError,",
            "  RateLimitError,",
            "  ValidationError,",
            "} from \"./errors\";",
        ]

        # Collect model imports
        model_refs = self._collect_model_refs(api)
        if model_refs:
            imports = ", ".join(sorted(model_refs))
            lines.append(f'import type {{ {imports} }} from "./models";')
        lines.append("")

        # Interceptor types
        lines.extend([
            "export type RequestInterceptor = (config: RequestConfig) => RequestConfig | Promise<RequestConfig>;",
            "export type ResponseInterceptor = (response: Response, config: RequestConfig) => Response | Promise<Response>;",
            "",
            "export interface RequestConfig {",
            "  method: string;",
            "  url: string;",
            "  headers: Record<string, string>;",
            "  body?: unknown;",
            "  params?: Record<string, string>;",
            "}",
            "",
            "export interface ClientOptions {",
            "  baseUrl: string;",
            "  auth?: AuthProvider;",
            "  maxRetries?: number;",
            "  retryDelay?: number;",
            "  timeout?: number;",
            "  requestInterceptors?: RequestInterceptor[];",
            "  responseInterceptors?: ResponseInterceptor[];",
            "}",
            "",
            "export interface PaginatedResponse<T> {",
            "  items: T[];",
            "  total: number;",
            "  page: number;",
            "  pageSize: number;",
            "  hasMore: boolean;",
            "}",
            "",
        ])

        # Client class
        lines.extend([
            "export class Client {",
            "  private baseUrl: string;",
            "  private auth: AuthProvider | null;",
            "  private maxRetries: number;",
            "  private retryDelay: number;",
            "  private timeout: number;",
            "  private requestInterceptors: RequestInterceptor[];",
            "  private responseInterceptors: ResponseInterceptor[];",
            "",
            "  constructor(options: ClientOptions) {",
            '    this.baseUrl = options.baseUrl.replace(/\\/$/, "");',
            "    this.auth = options.auth ?? null;",
            "    this.maxRetries = options.maxRetries ?? 3;",
            "    this.retryDelay = options.retryDelay ?? 500;",
            "    this.timeout = options.timeout ?? 30000;",
            "    this.requestInterceptors = options.requestInterceptors ?? [];",
            "    this.responseInterceptors = options.responseInterceptors ?? [];",
            "  }",
            "",
        ])

        # Private request method with retry
        lines.extend([
            "  private async request<T>(config: RequestConfig): Promise<T> {",
            "    let cfg = { ...config };",
            "",
            "    // Apply request interceptors",
            "    for (const interceptor of this.requestInterceptors) {",
            "      cfg = await interceptor(cfg);",
            "    }",
            "",
            "    // Apply auth headers",
            "    if (this.auth) {",
            "      const authHeaders = await this.auth.getHeaders();",
            "      cfg.headers = { ...cfg.headers, ...authHeaders };",
            "    }",
            "",
            "    let lastError: Error | null = null;",
            "",
            "    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {",
            "      if (attempt > 0) {",
            "        const delay = this.retryDelay * Math.pow(2, attempt - 1);",
            "        await new Promise((r) => setTimeout(r, delay));",
            "      }",
            "",
            "      try {",
            "        const url = new URL(`${this.baseUrl}${cfg.url}`);",
            "        if (cfg.params) {",
            "          Object.entries(cfg.params).forEach(([k, v]) => url.searchParams.set(k, v));",
            "        }",
            "",
            "        const controller = new AbortController();",
            "        const timeoutId = setTimeout(() => controller.abort(), this.timeout);",
            "",
            "        let response = await fetch(url.toString(), {",
            "          method: cfg.method,",
            "          headers: cfg.headers,",
            "          body: cfg.body ? JSON.stringify(cfg.body) : undefined,",
            "          signal: controller.signal,",
            "        });",
            "",
            "        clearTimeout(timeoutId);",
            "",
            "        // Apply response interceptors",
            "        for (const interceptor of this.responseInterceptors) {",
            "          response = await interceptor(response, cfg);",
            "        }",
            "",
            "        if (response.ok) {",
            "          if (response.status === 204) return undefined as T;",
            "          return await response.json() as T;",
            "        }",
            "",
            "        // Handle auth refresh on 401",
            "        if (response.status === 401 && attempt === 0 && this.auth?.onUnauthorized) {",
            "          await this.auth.onUnauthorized();",
            "          continue;",
            "        }",
            "",
            "        // Don't retry client errors (except 429)",
            "        if (response.status >= 400 && response.status < 500 && response.status !== 429) {",
            "          const body = await response.json().catch(() => null);",
            "          throw this.createError(response.status, body);",
            "        }",
            "",
            "        // Retry on 429 and 5xx",
            "        if (response.status === 429 || response.status >= 500) {",
            "          const body = await response.json().catch(() => null);",
            "          lastError = this.createError(response.status, body);",
            "          continue;",
            "        }",
            "",
            "        const body = await response.json().catch(() => null);",
            "        throw this.createError(response.status, body);",
            "",
            "      } catch (e) {",
            "        if (e instanceof APIError) throw e;",
            "        lastError = e instanceof Error ? e : new Error(String(e));",
            "        if (attempt === this.maxRetries) throw lastError;",
            "      }",
            "    }",
            "",
            '    throw lastError ?? new Error("Request failed");',
            "  }",
            "",
            "  private createError(status: number, body: unknown): APIError {",
            "    if (status === 401) return new AuthenticationError(undefined, body);",
            "    if (status === 404) return new NotFoundError(undefined, body);",
            "    if (status === 422) {",
            "      const errors = Array.isArray((body as Record<string, unknown>)?.errors)",
            "        ? (body as Record<string, unknown>).errors as Array<{ field: string; message: string }>",
            "        : [];",
            "      return new ValidationError(errors, body);",
            "    }",
            "    if (status === 429) {",
            "      return new RateLimitError(undefined, null, body);",
            "    }",
            "    return new APIError(`HTTP ${status}`, status, body);",
            "  }",
            "",
        ])

        # Pagination helper
        lines.extend([
            "  async *paginate<T>(",
            "    method: (params: { page: number; pageSize: number }) => Promise<PaginatedResponse<T>>,",
            "    pageSize = 20,",
            "  ): AsyncGenerator<T[], void> {",
            "    let page = 1;",
            "    let hasMore = true;",
            "    while (hasMore) {",
            "      const result = await method({ page, pageSize });",
            "      yield result.items;",
            "      hasMore = result.hasMore;",
            "      page++;",
            "    }",
            "  }",
            "",
        ])

        # File upload helper
        lines.extend([
            "  async uploadFile(",
            "    path: string,",
            "    file: File | Blob,",
            '    fieldName = "file",',
            "    extraFields?: Record<string, string>,",
            "  ): Promise<unknown> {",
            "    const formData = new FormData();",
            "    formData.append(fieldName, file);",
            "    if (extraFields) {",
            "      Object.entries(extraFields).forEach(([k, v]) => formData.append(k, v));",
            "    }",
            "",
            "    const headers: Record<string, string> = {};",
            "    if (this.auth) {",
            "      const authHeaders = await this.auth.getHeaders();",
            "      Object.assign(headers, authHeaders);",
            "    }",
            "",
            "    const resp = await fetch(`${this.baseUrl}${path}`, {",
            '      method: "POST",',
            "      headers,",
            "      body: formData,",
            "    });",
            "",
            "    if (!resp.ok) {",
            "      const body = await resp.json().catch(() => null);",
            "      throw this.createError(resp.status, body);",
            "    }",
            "    return resp.json();",
            "  }",
            "",
        ])

        # WebSocket helper
        lines.extend([
            "  createWebSocket(",
            "    path: string,",
            "    protocols?: string | string[],",
            "  ): WebSocket {",
            '    const wsUrl = this.baseUrl.replace(/^http/, "ws");',
            "    return new WebSocket(`${wsUrl}${path}`, protocols);",
            "  }",
            "",
        ])

        # Generate endpoint methods grouped by tag
        grouped = self._group_by_tag(api.endpoints)
        for tag, endpoints in grouped.items():
            for ep in endpoints:
                self._generate_endpoint_method(lines, ep, api)

        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def _generate_endpoint_method(
        self,
        lines: list[str],
        ep: Endpoint,
        api: ParsedAPI,
    ) -> None:
        """Generate a typed method for a single endpoint."""
        method_name = to_camel_case(sanitize_identifier(ep.operation_id))
        params: list[str] = []

        # Path params
        for p in ep.parameters:
            if p.location == "path":
                ts_type = openapi_type_to_ts(p.schema) if p.schema else "string"
                params.append(f"{to_camel_case(p.name)}: {ts_type}")

        # Request body
        body_type: str | None = None
        if ep.request_body_ref:
            body_type = to_pascal_case(sanitize_identifier(ep.request_body_ref))
            params.append(f"data: {body_type}")
        elif ep.request_body_schema and ep.request_body_schema.get("type") == "object":
            body_type = "Record<string, unknown>"
            params.append(f"data: {body_type}")

        # Query params
        query_params = [p for p in ep.parameters if p.location == "query"]
        if query_params:
            opts_fields: list[str] = []
            for qp in query_params:
                ts_type = openapi_type_to_ts(qp.schema) if qp.schema else "string"
                opt = "" if qp.required else "?"
                opts_fields.append(f"{to_camel_case(qp.name)}{opt}: {ts_type}")
            if opts_fields:
                params.append(f"params?: {{ {'; '.join(opts_fields)} }}")

        # Return type
        if ep.response_ref:
            return_type = to_pascal_case(sanitize_identifier(ep.response_ref))
        elif ep.response_schema:
            return_type = openapi_type_to_ts(ep.response_schema)
        else:
            return_type = "void"

        sig = ", ".join(params)
        if ep.summary:
            lines.append(f"  /** {ep.summary} */")
        lines.append(f"  async {method_name}({sig}): Promise<{return_type}> {{")

        # Build path with template literals
        path = ep.path
        path_params = [p for p in ep.parameters if p.location == "path"]
        if path_params:
            for p in path_params:
                path = path.replace(f"{{{p.name}}}", f"${{{to_camel_case(p.name)}}}")
            path_expr = f"`{path}`"
        else:
            path_expr = f'"{path}"'

        # Build request config
        lines.append(f"    return this.request<{return_type}>({{")
        lines.append(f'      method: "{ep.method}",')
        lines.append(f"      url: {path_expr},")
        lines.append('      headers: { "Content-Type": "application/json" },')
        if body_type:
            lines.append("      body: data,")
        if query_params:
            lines.append("      params: params as unknown as Record<string, string>,")
        lines.append("    });")
        lines.append("  }")
        lines.append("")

    def _generate_index(self, config: SDKConfig) -> str:
        lines = [
            "// Auto-generated by django_matt.sdkgen",
            "",
            'export { Client } from "./client";',
            'export type { ClientOptions, PaginatedResponse, RequestConfig, RequestInterceptor, ResponseInterceptor } from "./client";',
            'export { APIError, AuthenticationError, NotFoundError, RateLimitError, ValidationError } from "./errors";',
            'export { APIKeyAuth, JWTAuth } from "./auth";',
            'export type { AuthProvider } from "./auth";',
        ]
        if config.include_models:
            lines.append('export * from "./models";')
        lines.append("")
        return "\n".join(lines)

    def _generate_package_json(self, config: SDKConfig, api: ParsedAPI) -> str:
        pkg_name = to_kebab_case(config.package_name)
        pkg = {
            "name": pkg_name,
            "version": config.version,
            "description": config.description or f"TypeScript client for {api.title}",
            "main": "dist/index.js",
            "module": "dist/index.mjs",
            "types": "dist/index.d.ts",
            "files": ["dist"],
            "scripts": {
                "build": "tsup src/index.ts --format cjs,esm --dts",
                "lint": "tsc --noEmit",
            },
            "devDependencies": {
                "tsup": "^8.0.0",
                "typescript": "^5.4.0",
            },
            "license": config.license,
        }
        if config.author:
            pkg["author"] = config.author
        return json.dumps(pkg, indent=2) + "\n"

    def _generate_tsconfig(self) -> str:
        tsconfig = {
            "compilerOptions": {
                "target": "ES2022",
                "module": "ESNext",
                "moduleResolution": "bundler",
                "lib": ["ES2022", "DOM"],
                "strict": True,
                "declaration": True,
                "declarationMap": True,
                "sourceMap": True,
                "outDir": "dist",
                "rootDir": "src",
                "esModuleInterop": True,
                "skipLibCheck": True,
                "forceConsistentCasingInFileNames": True,
            },
            "include": ["src"],
        }
        return json.dumps(tsconfig, indent=2) + "\n"

    def _generate_readme(self, api: ParsedAPI, config: SDKConfig) -> str:
        pkg_name = to_kebab_case(config.package_name)
        return f"""\
# {pkg_name}

TypeScript client for {api.title} v{api.version}.

Auto-generated by django_matt.sdkgen.

## Installation

```bash
npm install {pkg_name}
```

## Usage

```typescript
import {{ Client, JWTAuth }} from "{pkg_name}";

const client = new Client({{
  baseUrl: "{config.base_url}",
  auth: new JWTAuth({{ accessToken: "your-token" }}),
}});
```

## Authentication

### JWT

```typescript
import {{ JWTAuth }} from "{pkg_name}";

const auth = new JWTAuth({{
  accessToken: "...",
  refreshToken: "...",
  refreshUrl: "{config.base_url}/auth/refresh",
}});
```

### API Key

```typescript
import {{ APIKeyAuth }} from "{pkg_name}";

const auth = new APIKeyAuth("your-api-key");
```
"""

    def _collect_model_refs(self, api: ParsedAPI) -> set[str]:
        """Collect all model type names referenced by endpoints."""
        refs: set[str] = set()
        for ep in api.endpoints:
            if ep.request_body_ref:
                refs.add(to_pascal_case(sanitize_identifier(ep.request_body_ref)))
            if ep.response_ref:
                refs.add(to_pascal_case(sanitize_identifier(ep.response_ref)))
        return refs

    @staticmethod
    def _group_by_tag(endpoints: list[Endpoint]) -> dict[str, list[Endpoint]]:
        grouped: dict[str, list[Endpoint]] = {}
        for ep in endpoints:
            tag = ep.tags[0] if ep.tags else "default"
            grouped.setdefault(tag, []).append(ep)
        return grouped
