# file-length-max: 550
"""
AI context file generators.

Generates CLAUDE.md, .cursorrules, and other AI assistant context files
from Django project introspection data.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

from django_matt.ai.ide.introspection import (
    ProjectInfo,
    ProjectIntrospector,
    get_project_structure,
)


class ClaudeMdGenerator:
    """
    Generates CLAUDE.md files for Claude Code and other AI assistants.

    Creates a comprehensive project context document that helps AI
    understand the codebase structure, conventions, and key files.

    Usage:
        generator = ClaudeMdGenerator()
        content = generator.generate()

        # Write to file
        generator.write("CLAUDE.md")
    """

    def __init__(
        self,
        introspector: ProjectIntrospector | None = None,
        include_models: bool = True,
        include_urls: bool = True,
        include_structure: bool = True,
        max_model_fields: int = 20,
    ):
        """
        Initialize generator.

        Args:
            introspector: Project introspector instance
            include_models: Include model definitions
            include_urls: Include URL patterns
            include_structure: Include file structure tree
            max_model_fields: Maximum fields to show per model
        """
        self.introspector = introspector or ProjectIntrospector()
        self.include_models = include_models
        self.include_urls = include_urls
        self.include_structure = include_structure
        self.max_model_fields = max_model_fields

    def generate(self, project_info: ProjectInfo | None = None) -> str:
        """Generate CLAUDE.md content."""
        if project_info is None:
            project_info = self.introspector.introspect()

        sections = [
            self._generate_header(project_info),
            self._generate_overview(project_info),
            self._generate_tech_stack(project_info),
        ]

        if self.include_structure:
            sections.append(self._generate_structure(project_info))

        if self.include_models:
            sections.append(self._generate_models(project_info))

        if self.include_urls:
            sections.append(self._generate_urls(project_info))

        sections.extend(
            [
                self._generate_conventions(project_info),
                self._generate_commands(project_info),
            ]
        )

        return "\n\n".join(filter(None, sections))

    def _generate_header(self, info: ProjectInfo) -> str:
        """Generate document header."""
        return f"""# {info.name} - AI Assistant Context

> Auto-generated by django-matt on {datetime.now().strftime("%Y-%m-%d")}
> This file provides context for AI assistants (Claude, Cursor, Copilot, etc.)"""

    def _generate_overview(self, info: ProjectInfo) -> str:
        """Generate project overview."""
        app_count = len(info.apps)
        model_count = sum(len(app.models) for app in info.apps)

        return f"""## Project Overview

- **Name**: {info.name}
- **Type**: Django Application
- **Apps**: {app_count} custom apps
- **Models**: {model_count} database models
- **Settings**: `{info.settings_module}`"""

    def _generate_tech_stack(self, info: ProjectInfo) -> str:
        """Generate tech stack section."""
        lines = [
            "## Tech Stack",
            "",
            f"- **Python**: {info.python_version}",
            f"- **Django**: {info.django_version}",
        ]

        # Database
        for name, engine in info.databases.items():
            lines.append(f"- **Database ({name})**: {engine}")

        # Key packages
        key_packages = [
            "django-matt",
            "djangorestframework",
            "django-ninja",
            "celery",
            "redis",
            "pytest",
            "pydantic",
        ]
        installed = {p.split("==")[0].lower(): p for p in info.installed_packages}

        for pkg in key_packages:
            if pkg in installed:
                lines.append(
                    f"- **{pkg}**: {installed[pkg].split('==')[1] if '==' in installed[pkg] else 'installed'}"
                )

        return "\n".join(lines)

    def _generate_structure(self, info: ProjectInfo) -> str:
        """Generate project structure tree."""
        structure = get_project_structure(info.root_path)

        def format_tree(tree: dict[str, Any], prefix: str = "") -> list[str]:
            lines = []
            items = list(tree.items())

            for i, (name, children) in enumerate(items):
                is_last = i == len(items) - 1
                connector = "└── " if is_last else "├── "
                lines.append(f"{prefix}{connector}{name}")

                if children:
                    extension = "    " if is_last else "│   "
                    lines.extend(format_tree(children, prefix + extension))

            return lines

        tree_lines = format_tree(structure)

        # Limit tree size
        if len(tree_lines) > 50:
            tree_lines = tree_lines[:50] + ["    ... (truncated)"]

        return "## Project Structure\n\n```\n" + "\n".join(tree_lines) + "\n```"

    def _generate_models(self, info: ProjectInfo) -> str:
        """Generate models documentation."""
        lines = ["## Data Models", ""]

        for app in info.apps:
            if not app.models:
                continue

            lines.append(f"### {app.label}")
            lines.append("")

            for model in app.models:
                lines.append(f"#### `{model.name}`")

                if model.docstring:
                    lines.append(f"_{model.docstring.split(chr(10))[0]}_")

                lines.append("")
                lines.append("| Field | Type | Notes |")
                lines.append("|-------|------|-------|")

                for field in model.fields[: self.max_model_fields]:
                    notes = []
                    if field.primary_key:
                        notes.append("PK")
                    if field.unique:
                        notes.append("unique")
                    if field.nullable:
                        notes.append("nullable")
                    if field.related_model:
                        notes.append(f"→ {field.related_model}")

                    lines.append(
                        f"| `{field.name}` | {field.field_type} | {', '.join(notes) or '-'} |"
                    )

                if len(model.fields) > self.max_model_fields:
                    lines.append(
                        f"| ... | | +{len(model.fields) - self.max_model_fields} more fields |"
                    )

                lines.append("")

        return "\n".join(lines) if len(lines) > 2 else ""

    def _generate_urls(self, info: ProjectInfo) -> str:
        """Generate URL patterns documentation."""
        all_urls = []
        for app in info.apps:
            all_urls.extend(app.urls)

        if not all_urls:
            return ""

        lines = [
            "## API Endpoints",
            "",
            "| Pattern | Name | View |",
            "|---------|------|------|",
        ]

        for url in all_urls[:30]:  # Limit to 30 URLs
            pattern = url.pattern.replace("<", "`<").replace(">", ">`")
            name = url.name or "-"
            lines.append(f"| `{pattern}` | {name} | {url.view_name} |")

        if len(all_urls) > 30:
            lines.append(f"| ... | | +{len(all_urls) - 30} more endpoints |")

        return "\n".join(lines)

    def _generate_conventions(self, info: ProjectInfo) -> str:
        """Generate coding conventions section."""
        return """## Coding Conventions

### Python Style
- Follow PEP 8 with 88-character line limit (Black formatter)
- Use type hints for function signatures
- Prefer `async def` for views when possible

### Django Patterns
- Models go in `models.py`, split into modules if large
- Use `get_object_or_404` for single object retrieval
- Prefer class-based views for complex logic
- Use Django's ORM; avoid raw SQL unless necessary

### API Design
- RESTful URL patterns (`/api/v1/resources/`)
- Use Pydantic schemas for request/response validation
- Return appropriate HTTP status codes
- Include pagination for list endpoints

### Testing
- Tests in `tests/` directory or `test_*.py` files
- Use pytest with pytest-django
- Mock external services in tests"""

    def _generate_commands(self, info: ProjectInfo) -> str:
        """Generate common commands section."""
        return """## Common Commands

```bash
# Development
python manage.py runserver
python manage.py migrate
python manage.py makemigrations

# Testing
pytest
pytest tests/ -v
pytest --cov=.

# Code Quality
ruff check .
ruff format .
mypy .

# Database
python manage.py dbshell
python manage.py shell_plus
```"""

    def write(self, path: str = "CLAUDE.md") -> Path:
        """Generate and write to file."""
        content = self.generate()
        file_path = Path(path)
        file_path.write_text(content)
        return file_path


class CursorRulesGenerator:
    """
    Generates .cursorrules files for Cursor IDE.

    Creates rules that help Cursor's AI understand project-specific
    conventions and preferences.

    Usage:
        generator = CursorRulesGenerator()
        content = generator.generate()
        generator.write(".cursorrules")
    """

    def __init__(
        self,
        introspector: ProjectIntrospector | None = None,
        framework_rules: bool = True,
        model_rules: bool = True,
    ):
        """
        Initialize generator.

        Args:
            introspector: Project introspector instance
            framework_rules: Include Django/django-matt specific rules
            model_rules: Include model-specific rules
        """
        self.introspector = introspector or ProjectIntrospector()
        self.framework_rules = framework_rules
        self.model_rules = model_rules

    def generate(self, project_info: ProjectInfo | None = None) -> str:
        """Generate .cursorrules content."""
        if project_info is None:
            project_info = self.introspector.introspect()

        rules = []

        # Project context
        rules.append(f"# Project: {project_info.name}")
        rules.append(
            f"# Django {project_info.django_version} with Python {project_info.python_version}"
        )
        rules.append("")

        # Framework rules
        if self.framework_rules:
            rules.extend(self._get_framework_rules())

        # Model-specific rules
        if self.model_rules:
            rules.extend(self._get_model_rules(project_info))

        # Import preferences
        rules.extend(self._get_import_rules(project_info))

        return "\n".join(rules)

    def _get_framework_rules(self) -> list[str]:
        """Get Django/django-matt framework rules."""
        return [
            "## Django & django-matt Framework Rules",
            "",
            "# API Views",
            "- Use `@api.get`, `@api.post` decorators for API endpoints",
            "- Use Pydantic `BaseModel` for request/response schemas",
            "- Use `async def` for database operations with `sync_to_async`",
            "- Return `Response` objects with appropriate status codes",
            "",
            "# Models",
            "- Define `__str__` method for all models",
            "- Use `related_name` for ForeignKey relationships",
            "- Add `class Meta` with `ordering` and `verbose_name`",
            "- Use `choices` for fields with limited options",
            "",
            "# Authentication",
            "- Use `@jwt_required` for protected endpoints",
            "- Access user via `request.user` after authentication",
            "- Use `IsAuthenticated`, `IsAdmin` permission classes",
            "",
            "# Database",
            "- Use `select_related` and `prefetch_related` to avoid N+1",
            "- Use `F()` expressions for atomic updates",
            "- Use `transaction.atomic()` for multiple related operations",
            "",
            "# Error Handling",
            "- Raise `ValidationAPIError` for validation failures",
            "- Raise `NotFoundAPIError` for missing resources",
            "- Use `APIError` base class for custom errors",
            "",
        ]

    def _get_model_rules(self, info: ProjectInfo) -> list[str]:
        """Get model-specific rules."""
        rules = ["## Project Models", ""]

        model_names = []
        for app in info.apps:
            for model in app.models:
                model_names.append(f"- `{model.full_name}`: {len(model.fields)} fields")

        if model_names:
            rules.append("# Available models:")
            rules.extend(model_names[:20])
            if len(model_names) > 20:
                rules.append(f"- ... and {len(model_names) - 20} more")
            rules.append("")

        return rules

    def _get_import_rules(self, info: ProjectInfo) -> list[str]:
        """Get import preference rules."""
        rules = [
            "## Import Preferences",
            "",
            "# Prefer these imports:",
            "from django_matt import DjangoMattAPI",
            "from django_matt.core import APIController, ModelSchema",
            "from django_matt.auth import jwt_required, IsAuthenticated",
            "from django_matt.views import ListView, CreateView, ReadView",
            "from pydantic import BaseModel, Field",
            "",
            "# For testing:",
            "import pytest",
            "from django_matt.testing import APITestClient",
            "",
        ]

        return rules

    def write(self, path: str = ".cursorrules") -> Path:
        """Generate and write to file."""
        content = self.generate()
        file_path = Path(path)
        file_path.write_text(content)
        return file_path


class AIContextGenerator:
    """
    Unified generator for all AI context files.

    Generates multiple context files in one operation.

    Usage:
        generator = AIContextGenerator()
        files = generator.generate_all()

        # Or generate specific files
        generator.generate_claude_md()
        generator.generate_cursorrules()
    """

    def __init__(
        self,
        output_dir: str | None = None,
        include_third_party: bool = False,
    ):
        """
        Initialize generator.

        Args:
            output_dir: Directory for output files (default: project root)
            include_third_party: Include third-party apps in analysis
        """
        self.output_dir = Path(output_dir) if output_dir else Path.cwd()
        self.introspector = ProjectIntrospector(include_third_party=include_third_party)
        self._project_info: ProjectInfo | None = None

    @property
    def project_info(self) -> ProjectInfo:
        """Get cached project info."""
        if self._project_info is None:
            self._project_info = self.introspector.introspect()
        return self._project_info

    def generate_claude_md(self, filename: str = "CLAUDE.md") -> Path:
        """Generate CLAUDE.md file."""
        generator = ClaudeMdGenerator(introspector=self.introspector)
        content = generator.generate(self.project_info)

        path = self.output_dir / filename
        path.write_text(content)
        return path

    def generate_cursorrules(self, filename: str = ".cursorrules") -> Path:
        """Generate .cursorrules file."""
        generator = CursorRulesGenerator(introspector=self.introspector)
        content = generator.generate(self.project_info)

        path = self.output_dir / filename
        path.write_text(content)
        return path

    def generate_all(self) -> dict[str, Path]:
        """Generate all context files."""
        return {
            "claude_md": self.generate_claude_md(),
            "cursorrules": self.generate_cursorrules(),
        }


__all__ = [
    "AIContextGenerator",
    "ClaudeMdGenerator",
    "CursorRulesGenerator",
]
